export interface GameDevTool {
  name: string;
  category: string;
  description: string;
  website: string;
  pricing: "free" | "freemium" | "paid" | "subscription" | "open_source";
  minSkillLevel: "beginner" | "intermediate" | "advanced" | "expert";
  platforms: string[];
  strengths: string[];
  weaknesses: string[];
  bestFor: string[];
  tags: string[];
}

export const GAME_DEV_TOOLS: GameDevTool[] = [
  // ENGINE
  {
    name: "Unity",
    category: "engine",
    description: "The world's most popular cross-platform game engine, used for 2D, 3D, VR, and AR games. C# scripting, massive asset store, excellent beginner support.",
    website: "https://unity.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "console", "vr"],
    strengths: ["Massive community & tutorials", "Huge Asset Store", "Excellent cross-platform support", "Strong 2D and 3D pipeline", "Visual scripting available"],
    weaknesses: ["Performance overhead vs native engines", "Licensing costs at scale", "Complex build pipeline", "Runtime fee controversy"],
    bestFor: ["mobile games", "indie games", "prototypes", "VR/AR", "cross-platform releases"],
    tags: ["2d", "3d", "mobile", "vr", "ar", "beginner-friendly", "c#"],
  },
  {
    name: "Unreal Engine",
    category: "engine",
    description: "AAA-quality 3D game engine by Epic Games. Industry standard for realistic graphics, large-scale games, and cinematics. Blueprints + C++ workflow.",
    website: "https://unrealengine.com",
    pricing: "free",
    minSkillLevel: "intermediate",
    platforms: ["pc", "console", "mobile", "vr"],
    strengths: ["Photorealistic graphics out of the box", "Nanite & Lumen rendering", "Blueprint visual scripting", "Free until $1M revenue", "AAA studio standard"],
    weaknesses: ["Steep learning curve", "Heavy resource requirements", "Complex project setup", "Overkill for simple 2D games", "Longer compile times"],
    bestFor: ["3d games", "realistic graphics", "shooters", "open world", "VR", "cinematics"],
    tags: ["3d", "aaa", "blueprints", "c++", "realistic", "console", "vr"],
  },
  {
    name: "Godot",
    category: "engine",
    description: "Free and open-source game engine with GDScript (Python-like) and C# support. Lightweight, excellent for 2D games, rapidly improving 3D pipeline.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "console"],
    strengths: ["Completely free & open source", "Lightweight & fast", "Excellent 2D pipeline", "Python-like GDScript easy to learn", "No revenue royalties ever"],
    weaknesses: ["3D still maturing vs Unity/Unreal", "Smaller community", "Fewer third-party assets", "Limited console support (needs platform SDK)"],
    bestFor: ["2d games", "indie games", "game jams", "open source projects", "learning game dev"],
    tags: ["2d", "3d", "open-source", "free", "beginner-friendly", "gdscript"],
  },
  {
    name: "GameMaker",
    category: "engine",
    description: "Specialized 2D game engine with GML scripting. Used to make classics like Undertale and Hotline Miami. Fast prototyping, beginner-friendly.",
    website: "https://gamemaker.io",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "console"],
    strengths: ["Purpose-built for 2D", "GML is easy to learn", "Fast iteration", "Proven for commercial 2D hits", "Good export options"],
    weaknesses: ["Not suited for 3D", "Subscription required for commercial use", "Less flexibility than general engines", "GML not transferable"],
    bestFor: ["2d games", "pixel art games", "game jams", "retro games", "platformers"],
    tags: ["2d", "pixel-art", "beginner-friendly", "gml", "retro"],
  },
  {
    name: "Phaser",
    category: "engine",
    description: "HTML5 game framework for browser-based 2D games using JavaScript/TypeScript. Excellent for web-native games and game jams.",
    website: "https://phaser.io",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["web"],
    strengths: ["Native web platform", "JavaScript/TypeScript", "No install required for players", "Great for web monetization", "Strong browser performance"],
    weaknesses: ["Web-only (no native mobile/desktop)", "JavaScript can be slow vs native", "Limited 3D support", "No visual editor"],
    bestFor: ["browser games", "web monetization", "web game jams", "html5 games"],
    tags: ["web", "html5", "javascript", "typescript", "2d", "browser"],
  },
  {
    name: "Cocos Creator",
    category: "engine",
    description: "Open-source engine focused on 2D and lightweight 3D with a component workflow and TypeScript scripting. Popular for mobile and web games, especially in Asia.",
    website: "https://www.cocos.com/en/creator",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web", "cross-platform"],
    strengths: ["Strong mobile performance", "TypeScript-first workflow", "Good 2D tooling", "Open-source core"],
    weaknesses: ["Smaller Western community", "Less AAA 3D tooling", "Plugin ecosystem smaller than Unity"],
    bestFor: ["mobile games", "2d games", "web exports", "performance-focused projects"],
    tags: ["2d", "3d", "mobile", "web", "typescript", "open-source"],
  },
  {
    name: "Defold",
    category: "engine",
    description: "Lightweight free engine with Lua scripting and strong 2D capabilities. Uses a component-based architecture and supports native, web, and mobile exports.",
    website: "https://defold.com",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "cross-platform"],
    strengths: ["Fast iteration", "Small runtime footprint", "Friendly editor", "No royalties"],
    weaknesses: ["Smaller asset ecosystem", "Limited high-end 3D workflows", "Fewer third-party tutorials"],
    bestFor: ["2d games", "mobile games", "indie projects", "game jams"],
    tags: ["2d", "lua", "mobile", "web", "game-jam", "beginner-friendly"],
  },
  {
    name: "LOVE",
    category: "engine",
    description: "Minimal open-source 2D framework using Lua. Code-first approach with a very fast feedback loop and excellent fit for prototyping and game jams.",
    website: "https://love2d.org",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Very lightweight", "Simple Lua API", "Great for rapid prototyping", "Strong jam community"],
    weaknesses: ["No built-in visual editor", "Framework-level tooling", "2D-focused only"],
    bestFor: ["2d prototypes", "game jams", "retro projects", "code-first workflows"],
    tags: ["2d", "lua", "open-source", "game-jam", "retro"],
  },
  {
    name: "Construct 3",
    category: "engine",
    description: "Browser-based no-code/low-code 2D game engine with event-sheet scripting. Fast onboarding for non-programmers and educators with web-first deployment.",
    website: "https://www.construct.net",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["web", "mobile", "pc"],
    strengths: ["Very beginner-friendly", "No-code event system", "Runs in browser", "Fast 2D prototyping"],
    weaknesses: ["Subscription cost", "Limited for complex architecture", "Less flexibility than code-heavy engines"],
    bestFor: ["beginner projects", "education", "2d games", "web games"],
    tags: ["2d", "beginner-friendly", "web", "rapid-prototyping"],
  },
  {
    name: "Bevy",
    category: "engine",
    description: "Modern open-source Rust game engine built around ECS architecture. High performance and strong systems-level control for teams comfortable with Rust.",
    website: "https://bevyengine.org",
    pricing: "open_source",
    minSkillLevel: "advanced",
    platforms: ["pc", "web", "mobile", "cross-platform"],
    strengths: ["High performance ECS", "Rust safety guarantees", "Modern architecture", "Open-source community"],
    weaknesses: ["Young ecosystem", "Steeper learning curve", "Tooling still maturing"],
    bestFor: ["performance-critical games", "rust projects", "engine programmers", "experimental systems"],
    tags: ["3d", "2d", "rust", "ecs", "open-source"],
  },
  // PROGRAMMING
  {
    name: "C# with .NET",
    category: "programming",
    description: "Primary scripting language for Unity. Strongly typed, modern OOP, excellent IDE tooling with Visual Studio or Rider.",
    website: "https://dotnet.microsoft.com",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web", "console"],
    strengths: ["Strongly typed reduces bugs", "Excellent IDE support", "Great performance", "Async/await built-in", "Rich ecosystem"],
    weaknesses: ["Steeper learning curve than GDScript", "Not directly portable outside Unity context"],
    bestFor: ["unity development", "large teams", "complex game systems"],
    tags: ["unity", "oop", "strongly-typed", "c#"],
  },
  {
    name: "GDScript",
    category: "programming",
    description: "Python-inspired scripting language native to Godot. Easy to learn, tightly integrated with the Godot editor and scene system.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Very easy to learn", "Deep Godot integration", "Fast iteration", "Clean Python-like syntax"],
    weaknesses: ["Not transferable outside Godot", "Performance below C# for heavy tasks"],
    bestFor: ["godot projects", "learning programming", "rapid prototyping"],
    tags: ["godot", "beginner-friendly", "scripting", "python-like"],
  },
  {
    name: "C++",
    category: "programming",
    description: "Low-level high-performance language used heavily in Unreal Engine and custom engine development. Offers deep control over memory and runtime behavior.",
    website: "https://isocpp.org",
    pricing: "open_source",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Top-tier performance", "Fine-grained control", "Industry standard for AAA", "Large ecosystem"],
    weaknesses: ["Complex syntax", "Manual memory pitfalls", "Longer iteration times"],
    bestFor: ["unreal development", "engine programming", "performance-critical gameplay"],
    tags: ["c++", "performance", "aaa", "systems"],
  },
  {
    name: "Lua",
    category: "programming",
    description: "Lightweight embeddable scripting language common in game engines and tooling. Easy to integrate and fast for iteration-heavy gameplay scripting.",
    website: "https://www.lua.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "cross-platform"],
    strengths: ["Small and fast", "Easy syntax", "Great for embedded scripting", "Proven in game stacks"],
    weaknesses: ["Limited static typing", "Smaller general ecosystem than JS/Python"],
    bestFor: ["scripting gameplay", "embedded tools", "rapid iteration"],
    tags: ["lua", "scripting", "beginner-friendly", "game-jam"],
  },
  {
    name: "JavaScript / TypeScript",
    category: "programming",
    description: "Primary language pair for web game development and many modern tooling pipelines. TypeScript adds static typing for larger codebases.",
    website: "https://www.typescriptlang.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["web", "pc", "mobile", "cross-platform"],
    strengths: ["Huge ecosystem", "Excellent web support", "Fast tooling", "TypeScript improves maintainability"],
    weaknesses: ["Runtime performance limits", "Package ecosystem churn", "Browser compatibility concerns"],
    bestFor: ["web games", "tools", "live-ops dashboards", "cross-platform frontends"],
    tags: ["javascript", "typescript", "web", "tooling", "beginner-friendly"],
  },
  {
    name: "Rust",
    category: "programming",
    description: "Systems language emphasizing memory safety and performance without garbage collection. Growing adoption in game engines and backend services.",
    website: "https://www.rust-lang.org",
    pricing: "open_source",
    minSkillLevel: "advanced",
    platforms: ["pc", "web", "mobile", "console", "cross-platform"],
    strengths: ["Memory safety", "High performance", "Strong compiler tooling", "Good for concurrent systems"],
    weaknesses: ["Steep learning curve", "Long compile times", "Smaller game middleware ecosystem"],
    bestFor: ["engine systems", "performance-critical code", "backend services"],
    tags: ["rust", "performance", "systems", "open-source"],
  },
  {
    name: "Haxe",
    category: "programming",
    description: "Cross-platform language that compiles to multiple targets including C++, JavaScript, and C#. Historically strong in 2D and web game workflows.",
    website: "https://haxe.org",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "web", "mobile", "console", "cross-platform"],
    strengths: ["Multi-target compilation", "Strong for cross-platform code reuse", "Mature in indie ecosystems"],
    weaknesses: ["Smaller talent pool", "Niche ecosystem", "Less mainstream tooling"],
    bestFor: ["cross-platform 2d games", "shared game logic", "indie pipelines"],
    tags: ["haxe", "cross-platform", "2d", "open-source"],
  },
  {
    name: "Python",
    category: "programming",
    description: "General-purpose language used in game tooling, automation, build scripts, and pipeline integration. Also common for AI tooling around game development.",
    website: "https://www.python.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "web", "cross-platform"],
    strengths: ["Very readable syntax", "Huge libraries", "Great automation language", "Strong AI ecosystem"],
    weaknesses: ["Not ideal for runtime performance", "Packaging complexity at scale"],
    bestFor: ["tooling scripts", "content pipelines", "automation", "ai workflows"],
    tags: ["python", "tooling", "ai", "automation", "beginner-friendly"],
  },
  // ART
  {
    name: "Aseprite",
    category: "art",
    description: "The industry-standard pixel art and animation tool for game developers. Tilemaps, spritesheet export, frame-by-frame animation.",
    website: "https://aseprite.org",
    pricing: "paid",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Purpose-built for pixel art", "Excellent animation workflow", "Tilemap support", "Sprite sheet export", "Affordable one-time price"],
    weaknesses: ["Pixel art only (no vector or raster painting)", "Niche tool", "One-time purchase (~$20)"],
    bestFor: ["pixel art games", "indie games", "retro aesthetics", "sprite animation"],
    tags: ["pixel-art", "2d", "animation", "sprites", "tiles"],
  },
  {
    name: "Blender",
    category: "art",
    description: "Free open-source 3D modeling, rigging, animation, and rendering suite. Used by indie studios worldwide for game assets.",
    website: "https://blender.org",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Completely free", "Full 3D pipeline (model, rig, animate, render)", "Strong community", "Game asset export (FBX, GLTF)", "Continuous improvements"],
    weaknesses: ["Steep learning curve", "Not optimized for game-real-time workflows", "Can be slow for very large assets"],
    bestFor: ["3d game assets", "character modeling", "environment art", "animations"],
    tags: ["3d", "modeling", "animation", "free", "open-source"],
  },
  {
    name: "Adobe Photoshop",
    category: "art",
    description: "Industry-standard raster image editor. Used for texture creation, UI assets, concept art, and post-processing.",
    website: "https://adobe.com/photoshop",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Industry standard", "Extensive features", "Great for textures and UI", "PSD file compatibility everywhere"],
    weaknesses: ["Expensive subscription", "Heavy software", "Overkill for pixel art", "Not 3D"],
    bestFor: ["texture creation", "UI art", "concept art", "professional studios"],
    tags: ["2d", "textures", "ui", "professional", "adobe"],
  },
  {
    name: "Krita",
    category: "art",
    description: "Free open-source digital painting application. Great for concept art, textures, and 2D game art with a professional brush engine.",
    website: "https://krita.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Free and open source", "Excellent brush engine", "Good for concept art and textures", "Animation support"],
    weaknesses: ["Less industry recognition than Photoshop", "Fewer plugins", "UI can feel dated"],
    bestFor: ["concept art", "2d art", "textures", "budget-conscious teams"],
    tags: ["2d", "painting", "concept-art", "free", "open-source"],
  },
  {
    name: "Substance Painter",
    category: "art",
    description: "Industry-standard texture painting suite for PBR materials on 3D assets. Offers real-time viewport feedback and exports tuned for major engines.",
    website: "https://www.adobe.com/products/substance3d-painter.html",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Excellent PBR workflow", "Smart masks and materials", "Strong engine export presets"],
    weaknesses: ["Subscription/license cost", "Focused on texturing only", "Requires solid UV workflow"],
    bestFor: ["3d texturing", "character assets", "environment materials"],
    tags: ["3d", "textures", "pbr", "professional"],
  },
  {
    name: "Substance Designer",
    category: "art",
    description: "Node-based procedural material authoring tool for creating reusable PBR materials. Widely used in production pipelines for scalable asset generation.",
    website: "https://www.adobe.com/products/substance3d-designer.html",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Procedural reusable materials", "Powerful node workflows", "Pipeline-friendly outputs"],
    weaknesses: ["Steep learning curve", "Best value in larger pipelines", "Subscription cost"],
    bestFor: ["material libraries", "environment production", "technical art workflows"],
    tags: ["3d", "materials", "node-based", "technical-art"],
  },
  {
    name: "ZBrush",
    category: "art",
    description: "Digital sculpting package used for high-detail character and creature creation. Commonly used to produce high-poly sculpts for bake-down game assets.",
    website: "https://www.maxon.net/zbrush",
    pricing: "paid",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Best-in-class sculpting", "Handles dense meshes", "Production-proven character pipeline"],
    weaknesses: ["Unique UI paradigm", "Steep learning curve", "Requires retopo/baking workflow"],
    bestFor: ["character sculpting", "creatures", "high-poly concept meshes"],
    tags: ["3d", "sculpting", "character-art", "advanced"],
  },
  {
    name: "Autodesk Maya",
    category: "art",
    description: "Comprehensive DCC suite for 3D modeling, rigging, and pipeline integration. Widely used in AAA and studio production environments.",
    website: "https://www.autodesk.com/products/maya",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Studio-standard pipeline tool", "Strong rigging and modeling", "Deep scripting support"],
    weaknesses: ["High subscription cost", "Steep learning curve", "Heavy software footprint"],
    bestFor: ["aaa pipelines", "character production", "team-based 3d workflows"],
    tags: ["3d", "modeling", "rigging", "professional", "aaa"],
  },
  {
    name: "Procreate",
    category: "art",
    description: "iPad-first digital painting app popular for concept sketches, UI mockups, and stylized 2D art ideation. Fast and intuitive for portable workflows.",
    website: "https://procreate.com",
    pricing: "paid",
    minSkillLevel: "beginner",
    platforms: ["mobile"],
    strengths: ["Very approachable UX", "Strong brush engine", "Great for ideation on the go"],
    weaknesses: ["iPad-only", "Not a full pipeline suite", "Limited advanced production tooling"],
    bestFor: ["concept sketches", "2d ideation", "art direction drafts"],
    tags: ["2d", "painting", "concept-art", "beginner-friendly"],
  },
  {
    name: "Pyxel Edit",
    category: "art",
    description: "Tile-focused pixel art editor built for fast environment and tileset creation. Popular in retro and top-down indie projects.",
    website: "https://pyxeledit.com",
    pricing: "paid",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Great tilemap workflow", "Simple focused UI", "Good for environment art"],
    weaknesses: ["Narrow scope vs Aseprite", "Smaller community", "Limited non-pixel use"],
    bestFor: ["tilemap production", "pixel environments", "retro projects"],
    tags: ["pixel-art", "2d", "tiles", "retro", "beginner-friendly"],
  },
  // ANIMATION
  {
    name: "Spine",
    category: "animation",
    description: "Professional 2D skeletal animation tool widely used in game development. Runtime available for Unity, Godot, and more.",
    website: "http://esotericsoftware.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Industry standard 2D skeletal animation", "Runtime available for major engines", "Powerful mesh deformation", "Smooth animations with small file sizes"],
    weaknesses: ["Significant cost (~$100-300)", "Learning curve for advanced features", "Runtime integrations require setup"],
    bestFor: ["2d character animation", "mobile games", "action games"],
    tags: ["2d", "skeletal-animation", "mobile", "character"],
  },
  {
    name: "DragonBones",
    category: "animation",
    description: "Free 2D skeletal animation tool similar to Spine. Good for mobile game character animation with engine integrations.",
    website: "http://dragonbones.com",
    pricing: "free",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Free alternative to Spine", "Good engine integrations", "Active development"],
    weaknesses: ["Less community support than Spine", "Fewer tutorials", "Documentation quality varies"],
    bestFor: ["2d animation", "budget projects", "mobile games"],
    tags: ["2d", "skeletal-animation", "free", "mobile"],
  },
  {
    name: "Cascadeur",
    category: "animation",
    description: "3D keyframe animation software with physics-assisted posing and auto-physics features. Useful for more natural character motion without full mocap sessions.",
    website: "https://cascadeur.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Physics-assisted posing", "Good for action animation", "Indie-accessible pricing"],
    weaknesses: ["Narrow focus vs full DCC tools", "Pipeline integration setup required"],
    bestFor: ["character animation", "combat moves", "indie 3d projects"],
    tags: ["3d", "character", "physics", "animation"],
  },
  {
    name: "Mixamo",
    category: "animation",
    description: "Adobe service for automatic character rigging and a large library of mocap animations. Speeds up prototyping and placeholder animation work.",
    website: "https://www.mixamo.com",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Fast auto-rigging", "Large animation library", "Great prototyping speed"],
    weaknesses: ["Generic motion style", "Limited deep customization", "External workflow step"],
    bestFor: ["prototype animation", "indie teams", "placeholder character motion"],
    tags: ["3d", "mocap", "character", "beginner-friendly"],
  },
  {
    name: "Live2D Cubism",
    category: "animation",
    description: "2D mesh deformation and rigging system used for anime-style character motion. Common in visual novels, mobile RPGs, and VTuber-adjacent workflows.",
    website: "https://www.live2d.com/en/cubism",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web"],
    strengths: ["High-quality 2D character motion", "Efficient runtime output", "Strong stylized character support"],
    weaknesses: ["Specialized workflow", "License cost", "Learning curve for rig structure"],
    bestFor: ["visual novels", "anime-style characters", "mobile rpg ui characters"],
    tags: ["2d", "character", "rigging", "mobile"],
  },
  {
    name: "Maya Animation",
    category: "animation",
    description: "Maya's professional animation toolset for rigging, keyframing, and cinematic character workflows. Standard in many studio animation pipelines.",
    website: "https://www.autodesk.com/products/maya",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Production-proven pipeline", "Deep rigging tools", "Strong cinematic support"],
    weaknesses: ["High cost", "Steep onboarding", "Complex setup for solo creators"],
    bestFor: ["studio pipelines", "character animation", "cinematic sequences"],
    tags: ["3d", "animation", "rigging", "professional", "aaa"],
  },
  // UI / HUD
  {
    name: "Unity UI Toolkit",
    category: "ui",
    description: "Unity's modern UI system using UXML/USS (similar to HTML/CSS). Best for complex, scalable game UI and tooling.",
    website: "https://unity.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console"],
    strengths: ["Modern declarative UI", "CSS-like styling", "Good for complex UI", "Editor tool UI built with it too"],
    weaknesses: ["Newer system with some gaps", "Learning curve for traditional game devs", "3D world-space UI needs workarounds"],
    bestFor: ["complex game ui", "menus", "hud systems", "unity projects"],
    tags: ["ui", "unity", "declarative", "css-like"],
  },
  {
    name: "Godot Control Nodes",
    category: "ui",
    description: "Godot's built-in UI system using Control nodes in the scene tree. Straightforward, integrated with everything Godot.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Deeply integrated with Godot", "Theme system", "Responsive layout", "Easy to learn"],
    weaknesses: ["Godot-only", "Less powerful than web-based UI solutions"],
    bestFor: ["godot projects", "menus", "hud", "game ui"],
    tags: ["ui", "godot", "beginner-friendly"],
  },
  {
    name: "NoesisGUI",
    category: "ui",
    description: "XAML-based retained-mode UI middleware for games with strong runtime performance and tooling. Used when teams want scalable app-like UI patterns in games.",
    website: "https://www.noesisengine.com",
    pricing: "paid",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["High-performance runtime UI", "Powerful data binding", "Scalable for complex HUD/menu systems"],
    weaknesses: ["License cost", "Advanced setup", "Smaller community than engine-native UI"],
    bestFor: ["complex hud", "cross-platform ui", "studio ui architecture"],
    tags: ["ui", "hud", "cross-platform", "realtime"],
  },
  {
    name: "Rive",
    category: "ui",
    description: "Real-time interactive animation and UI tool for runtime motion graphics. Useful for polished menus, onboarding flows, and animated HUD elements.",
    website: "https://rive.app",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["web", "mobile", "pc", "cross-platform"],
    strengths: ["Interactive runtime animation", "Compact vector-based assets", "Good cross-platform runtimes"],
    weaknesses: ["Extra integration step", "Advanced states require planning"],
    bestFor: ["animated ui", "polished menus", "interactive hud elements"],
    tags: ["ui", "animation", "realtime", "cross-platform"],
  },
  // VFX
  {
    name: "Unity VFX Graph",
    category: "vfx",
    description: "Node-based visual effects editor for Unity's High Definition and Universal Render Pipelines. GPU-accelerated particle systems.",
    website: "https://unity.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "console"],
    strengths: ["GPU-accelerated", "Node-based (no code)", "Extremely powerful", "Integrates with Unity render pipelines"],
    weaknesses: ["Requires HDRP or URP", "Not mobile-friendly", "Steep learning curve", "Heavy GPU requirements"],
    bestFor: ["3d vfx", "realistic effects", "aaa-style games", "pc/console"],
    tags: ["vfx", "particles", "unity", "gpu", "node-based"],
  },
  {
    name: "Godot Particles",
    category: "vfx",
    description: "Godot's built-in particle system for 2D and 3D effects. CPU and GPU modes available, integrated with Godot's scene system.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Built into Godot", "Easy to use", "CPU and GPU modes", "Good for indie games"],
    weaknesses: ["Less powerful than Unity VFX Graph", "Limited shader customization"],
    bestFor: ["2d vfx", "indie game effects", "godot projects"],
    tags: ["vfx", "particles", "godot", "2d"],
  },
  {
    name: "After Effects",
    category: "vfx",
    description: "Adobe's motion graphics and compositing tool. Used for cinematic cutscene VFX and UI animations. Not real-time but exports to sprite sheets.",
    website: "https://adobe.com/after-effects",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Industry-standard motion graphics", "Sprite sheet export plugins", "Huge tutorial library"],
    weaknesses: ["Not real-time", "Expensive subscription", "Requires export to use in engine"],
    bestFor: ["cutscenes", "ui animations", "marketing material", "sprite sheet vfx"],
    tags: ["vfx", "motion-graphics", "2d", "adobe", "cinematic"],
  },
  {
    name: "Niagara (UE5)",
    category: "vfx",
    description: "Unreal Engine 5's advanced node-based VFX framework for particles, simulations, and gameplay-reactive effects. Built for high-fidelity real-time visuals.",
    website: "https://www.unrealengine.com",
    pricing: "free",
    minSkillLevel: "advanced",
    platforms: ["pc", "console", "mobile", "vr"],
    strengths: ["Deep UE5 integration", "Powerful data-driven effects", "AAA-quality real-time visuals"],
    weaknesses: ["Complex system", "Heavy for simple projects", "UE-focused workflow"],
    bestFor: ["unreal projects", "high-end 3d vfx", "gameplay-reactive particles"],
    tags: ["vfx", "unreal", "niagara", "3d", "realtime", "aaa"],
  },
  {
    name: "Houdini",
    category: "vfx",
    description: "Procedural 3D and VFX suite used for advanced simulations, destruction, and technical art pipelines. Houdini Engine enables integration into game editors.",
    website: "https://www.sidefx.com/products/houdini",
    pricing: "subscription",
    minSkillLevel: "expert",
    platforms: ["pc"],
    strengths: ["Best-in-class procedural workflows", "Advanced simulation tools", "Scales to complex production"],
    weaknesses: ["Very steep learning curve", "High complexity", "Expensive for small teams"],
    bestFor: ["technical art", "procedural worlds", "simulation-heavy pipelines"],
    tags: ["vfx", "procedural", "simulation", "technical-art", "3d"],
  },
  {
    name: "EmberGen",
    category: "vfx",
    description: "Real-time volumetric fluid and smoke simulation tool used to author explosions, fire, and clouds. Exports baked assets for engine use.",
    website: "https://jangafx.com/software/embergen",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Fast real-time iteration", "High-quality volumetrics", "Good export options for games"],
    weaknesses: ["Specialized scope", "Paid license", "Requires integration into engine pipeline"],
    bestFor: ["explosions", "fire and smoke effects", "cinematic vfx assets"],
    tags: ["vfx", "volumetric", "realtime", "3d"],
  },
  // VERSION CONTROL
  {
    name: "Git + GitHub",
    category: "version_control",
    description: "The standard version control system for code. GitHub provides hosting, pull requests, and CI/CD integrations.",
    website: "https://github.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Industry standard", "Free for small teams", "Massive ecosystem", "Great for code", "GitHub Actions CI/CD"],
    weaknesses: ["Poor at handling large binary files (art, audio)", "Need Git LFS for binaries (extra cost)", "Command line can be daunting for beginners"],
    bestFor: ["code versioning", "solo projects", "small teams", "open source"],
    tags: ["version-control", "git", "collaboration", "ci-cd"],
  },
  {
    name: "Plastic SCM (Unity DevOps)",
    category: "version_control",
    description: "Version control designed for game development with large binary file support. Now integrated into Unity DevOps.",
    website: "https://unity.com/products/plastic-scm",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Handles large binary files natively", "Good GUI", "Designed for game teams", "Branch and merge for artists"],
    weaknesses: ["Learning curve", "Cost at scale", "Unity ecosystem only effectively"],
    bestFor: ["unity projects", "teams with artists", "large binary assets"],
    tags: ["version-control", "unity", "binary-files", "teams"],
  },
  {
    name: "Perforce Helix Core",
    category: "version_control",
    description: "Enterprise version control system widely used in AAA game studios for very large binary assets and multi-site collaboration.",
    website: "https://www.perforce.com/products/helix-core",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc", "cross-platform"],
    strengths: ["Excellent large binary handling", "Scales to massive depots", "Strong permissions/workflow controls"],
    weaknesses: ["Operational complexity", "Infrastructure/admin overhead", "Cost at scale"],
    bestFor: ["aaa teams", "large asset repositories", "studio pipelines"],
    tags: ["version-control", "binary-files", "teams", "enterprise"],
  },
  {
    name: "GitLab",
    category: "version_control",
    description: "Git hosting platform with integrated CI/CD, issue tracking, and self-hosting options. Useful for teams needing all-in-one DevOps workflows.",
    website: "https://gitlab.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "cross-platform"],
    strengths: ["Integrated CI/CD", "Self-hosting available", "Strong project management tooling"],
    weaknesses: ["Git binary limitations still apply", "Can be heavy to administer self-hosted"],
    bestFor: ["devops workflows", "self-hosted teams", "code collaboration"],
    tags: ["version-control", "git", "ci-cd", "cloud"],
  },
  {
    name: "Diversion",
    category: "version_control",
    description: "Game-focused source control aimed at artist-friendly binary workflows and simpler collaboration UX than traditional Git setups.",
    website: "https://www.diversion.dev",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Artist-friendly workflow", "Simplified setup", "Built for game assets"],
    weaknesses: ["Newer ecosystem", "Smaller community", "Fewer mature integrations"],
    bestFor: ["small game teams", "binary asset collaboration", "indie production"],
    tags: ["version-control", "binary-files", "beginner-friendly", "collaboration"],
  },
  // DEPLOYMENT
  {
    name: "Steam",
    category: "deployment",
    description: "The dominant PC gaming platform by Valve. Required for most commercial PC game releases. Steamworks SDK for DRM, achievements, leaderboards.",
    website: "https://store.steampowered.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Largest PC gaming marketplace", "Built-in community features", "Sales events driving huge revenue", "Workshop modding support"],
    weaknesses: ["$100 one-time fee per game", "30% revenue cut", "Discovery can be difficult", "Review process required"],
    bestFor: ["pc games", "commercial releases", "indie games"],
    tags: ["deployment", "pc", "commercial", "marketplace"],
  },
  {
    name: "itch.io",
    category: "deployment",
    description: "Open indie game marketplace. Zero upfront cost, flexible revenue sharing, excellent for game jams and indie releases.",
    website: "https://itch.io",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["pc", "web"],
    strengths: ["Free to publish", "Flexible pricing (even free)", "Great game jam community", "Supports pay-what-you-want", "Web game hosting"],
    weaknesses: ["Smaller audience than Steam", "Less discovery infrastructure", "No built-in DRM"],
    bestFor: ["game jams", "free games", "indie experiments", "web games", "demo releases"],
    tags: ["deployment", "indie", "free", "game-jam", "web"],
  },
  {
    name: "Google Play Store",
    category: "deployment",
    description: "Android's primary app and game marketplace. Required for commercial Android game distribution.",
    website: "https://play.google.com/console",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["mobile"],
    strengths: ["2.5B Android users", "Lower entry barrier than Apple", "$25 one-time fee", "Easier sideloading"],
    weaknesses: ["30% revenue cut (reduces to 15% over $1M)", "Review process", "Fragmented Android devices", "More piracy than iOS"],
    bestFor: ["android games", "mobile games", "free-to-play"],
    tags: ["deployment", "android", "mobile", "commercial"],
  },
  {
    name: "Apple App Store",
    category: "deployment",
    description: "iOS and macOS app marketplace. Required for commercial iOS game distribution. Strict review process.",
    website: "https://developer.apple.com",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["mobile"],
    strengths: ["High-spending user base", "Better security reputation", "Mac + iOS unified distribution", "Good discovery algorithms"],
    weaknesses: ["$99/year developer fee", "Strict review guidelines", "30% revenue cut", "Requires Mac for builds"],
    bestFor: ["ios games", "premium mobile games", "high-revenue mobile"],
    tags: ["deployment", "ios", "mobile", "apple"],
  },
  {
    name: "Epic Games Store",
    category: "deployment",
    description: "PC game storefront by Epic with favorable revenue share terms and growing audience. Includes developer portal tooling and store integrations.",
    website: "https://store.epicgames.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Favorable revenue split", "Strong PC audience", "Epic ecosystem integration"],
    weaknesses: ["Smaller audience than Steam", "Curation/release requirements", "Lower discoverability tools"],
    bestFor: ["pc commercial releases", "indie-to-midcore launches", "epic ecosystem titles"],
    tags: ["deployment", "pc", "commercial", "marketplace"],
  },
  {
    name: "GOG Connect / GOG Galaxy",
    category: "deployment",
    description: "GOG distribution ecosystem focused on DRM-free PC releases and community trust. GOG Galaxy provides launcher and user account integration.",
    website: "https://www.gog.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["DRM-free positioning", "Loyal PC audience", "Strong fit for premium titles"],
    weaknesses: ["Smaller install base than Steam", "Selective onboarding", "Fewer live-service features"],
    bestFor: ["premium pc games", "drm-free releases", "catalog distribution"],
    tags: ["deployment", "pc", "commercial", "drm-free"],
  },
  {
    name: "Xbox / PlayStation / Nintendo Partner Portals",
    category: "deployment",
    description: "Official console publishing portals and certification pipelines for Xbox, PlayStation, and Nintendo platforms. Required path for commercial console releases.",
    website: "https://developer.microsoft.com/games",
    pricing: "paid",
    minSkillLevel: "advanced",
    platforms: ["console"],
    strengths: ["Required for console launch", "Access to platform SDK and certification docs", "First-party publishing support"],
    weaknesses: ["Strict certification requirements", "Long lead times", "Higher business/legal overhead"],
    bestFor: ["console launches", "certification workflows", "cross-platform commercial releases"],
    tags: ["deployment", "console", "certification", "commercial"],
  },
  {
    name: "CrazyGames",
    category: "deployment",
    description: "Web game platform for instant-play HTML5 games with built-in distribution and monetization opportunities. Strong for rapid browser game launches.",
    website: "https://www.crazygames.com",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Fast web distribution", "Large browser audience", "Good fit for lightweight games"],
    weaknesses: ["Web-only constraints", "Platform-specific monetization model", "Short session focus"],
    bestFor: ["html5 games", "casual web titles", "rapid release cycles"],
    tags: ["deployment", "web", "browser", "game-jam"],
  },
  {
    name: "Poki",
    category: "deployment",
    description: "Web game publishing platform with a focus on polished, quick-loading browser experiences. Offers access to a broad casual audience.",
    website: "https://poki.com",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Large casual web audience", "Web-focused distribution", "Good for lightweight gameplay loops"],
    weaknesses: ["Web-only scope", "Editorial acceptance requirements", "Limited fit for deep premium games"],
    bestFor: ["casual web games", "html5 launches", "browser-first titles"],
    tags: ["deployment", "web", "browser", "casual"],
  },
  // AI TOOLING
  {
    name: "GitHub Copilot",
    category: "ai_tooling",
    description: "AI pair programmer integrated into VS Code, Visual Studio, JetBrains IDEs. Autocompletes code, suggests implementations, writes tests.",
    website: "https://github.com/features/copilot",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Excellent code autocomplete", "Works in your existing IDE", "Speeds up boilerplate", "Good at explaining code"],
    weaknesses: ["Monthly subscription cost", "Can suggest incorrect code", "Privacy concerns", "Less useful for engine-specific patterns"],
    bestFor: ["code generation", "all skill levels", "script writing", "productivity"],
    tags: ["ai", "code-generation", "ide", "productivity"],
  },
  {
    name: "Midjourney",
    category: "ai_tooling",
    description: "AI image generation tool via Discord. Produces high-quality concept art, textures, and visual references for game development.",
    website: "https://midjourney.com",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Extremely high quality output", "Fast concept generation", "Great for visual references", "Consistent art styles"],
    weaknesses: ["Subscription required", "Discord-based UI is awkward", "Commercial license terms vary", "Not pixel art focused"],
    bestFor: ["concept art", "texture references", "art direction", "prototyping visuals"],
    tags: ["ai", "art-generation", "concept-art", "textures"],
  },
  {
    name: "ChatGPT / GPT-4",
    category: "ai_tooling",
    description: "General-purpose AI assistant by OpenAI. Useful for game design brainstorming, dialog writing, game mechanics analysis, and code debugging.",
    website: "https://chat.openai.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Versatile: design, writing, code, analysis", "Free tier available", "Good at game design consulting", "Explains complex concepts"],
    weaknesses: ["Not game-engine specific", "Can hallucinate API details", "Requires good prompting"],
    bestFor: ["game design", "dialog writing", "brainstorming", "code help", "documentation"],
    tags: ["ai", "writing", "design", "brainstorming", "code-help"],
  },
];

export const TOOL_CATEGORIES = [
  { id: "engine", label: "Game Engine", description: "Core engine powering your game's rendering, physics, and scene management" },
  { id: "programming", label: "Programming Language", description: "Primary scripting and programming language for game logic" },
  { id: "art", label: "Art & Assets", description: "Tools for creating 2D/3D art, textures, and visual assets" },
  { id: "animation", label: "Animation", description: "Character and object animation tools" },
  { id: "ui", label: "UI / HUD", description: "User interface and heads-up display systems" },
  { id: "vfx", label: "VFX & Particles", description: "Visual effects, particle systems, and post-processing" },
  { id: "version_control", label: "Version Control", description: "Source control and collaboration for code and assets" },
  { id: "deployment", label: "Deployment & Distribution", description: "Platforms and stores for publishing your game" },
  { id: "ai_tooling", label: "AI Tooling", description: "AI-powered tools for accelerating development" },
];
