export interface GameDevTool {
  name: string;
  category: string;
  description: string;
  website: string;
  pricing: "free" | "freemium" | "paid" | "subscription" | "open_source";
  minSkillLevel: "beginner" | "intermediate" | "advanced" | "expert";
  platforms: string[];
  strengths: string[];
  weaknesses: string[];
  bestFor: string[];
  tags: string[];
}

export const GAME_DEV_TOOLS: GameDevTool[] = [
  // ENGINE
  {
    name: "Unity",
    category: "engine",
    description: "The world's most popular cross-platform game engine, used for 2D, 3D, VR, and AR games. C# scripting, massive asset store, excellent beginner support.",
    website: "https://unity.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "console", "vr"],
    strengths: ["Massive community & tutorials", "Huge Asset Store", "Excellent cross-platform support", "Strong 2D and 3D pipeline", "Visual scripting available"],
    weaknesses: ["Performance overhead vs native engines", "Licensing costs at scale", "Complex build pipeline", "Runtime fee controversy"],
    bestFor: ["mobile games", "indie games", "prototypes", "VR/AR", "cross-platform releases"],
    tags: ["2d", "3d", "mobile", "vr", "ar", "beginner-friendly", "c#"],
  },
  {
    name: "Unreal Engine",
    category: "engine",
    description: "AAA-quality 3D game engine by Epic Games. Industry standard for realistic graphics, large-scale games, and cinematics. Blueprints + C++ workflow.",
    website: "https://unrealengine.com",
    pricing: "free",
    minSkillLevel: "intermediate",
    platforms: ["pc", "console", "mobile", "vr"],
    strengths: ["Photorealistic graphics out of the box", "Nanite & Lumen rendering", "Blueprint visual scripting", "Free until $1M revenue", "AAA studio standard"],
    weaknesses: ["Steep learning curve", "Heavy resource requirements", "Complex project setup", "Overkill for simple 2D games", "Longer compile times"],
    bestFor: ["3d games", "realistic graphics", "shooters", "open world", "VR", "cinematics"],
    tags: ["3d", "aaa", "blueprints", "c++", "realistic", "console", "vr"],
  },
  {
    name: "Godot",
    category: "engine",
    description: "Free and open-source game engine with GDScript (Python-like) and C# support. Lightweight, excellent for 2D games, rapidly improving 3D pipeline.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "console"],
    strengths: ["Completely free & open source", "Lightweight & fast", "Excellent 2D pipeline", "Python-like GDScript easy to learn", "No revenue royalties ever"],
    weaknesses: ["3D still maturing vs Unity/Unreal", "Smaller community", "Fewer third-party assets", "Limited console support (needs platform SDK)"],
    bestFor: ["2d games", "indie games", "game jams", "open source projects", "learning game dev"],
    tags: ["2d", "3d", "open-source", "free", "beginner-friendly", "gdscript"],
  },
  {
    name: "GameMaker",
    category: "engine",
    description: "Specialized 2D game engine with GML scripting. Used to make classics like Undertale and Hotline Miami. Fast prototyping, beginner-friendly.",
    website: "https://gamemaker.io",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "console"],
    strengths: ["Purpose-built for 2D", "GML is easy to learn", "Fast iteration", "Proven for commercial 2D hits", "Good export options"],
    weaknesses: ["Not suited for 3D", "Subscription required for commercial use", "Less flexibility than general engines", "GML not transferable"],
    bestFor: ["2d games", "pixel art games", "game jams", "retro games", "platformers"],
    tags: ["2d", "pixel-art", "beginner-friendly", "gml", "retro"],
  },
  {
    name: "Phaser",
    category: "engine",
    description: "HTML5 game framework for browser-based 2D games using JavaScript/TypeScript. Excellent for web-native games and game jams.",
    website: "https://phaser.io",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["web"],
    strengths: ["Native web platform", "JavaScript/TypeScript", "No install required for players", "Great for web monetization", "Strong browser performance"],
    weaknesses: ["Web-only (no native mobile/desktop)", "JavaScript can be slow vs native", "Limited 3D support", "No visual editor"],
    bestFor: ["browser games", "web monetization", "web game jams", "html5 games"],
    tags: ["web", "html5", "javascript", "typescript", "2d", "browser"],
  },
  // PROGRAMMING
  {
    name: "C# with .NET",
    category: "programming",
    description: "Primary scripting language for Unity. Strongly typed, modern OOP, excellent IDE tooling with Visual Studio or Rider.",
    website: "https://dotnet.microsoft.com",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web", "console"],
    strengths: ["Strongly typed reduces bugs", "Excellent IDE support", "Great performance", "Async/await built-in", "Rich ecosystem"],
    weaknesses: ["Steeper learning curve than GDScript", "Not directly portable outside Unity context"],
    bestFor: ["unity development", "large teams", "complex game systems"],
    tags: ["unity", "oop", "strongly-typed", "c#"],
  },
  {
    name: "GDScript",
    category: "programming",
    description: "Python-inspired scripting language native to Godot. Easy to learn, tightly integrated with the Godot editor and scene system.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Very easy to learn", "Deep Godot integration", "Fast iteration", "Clean Python-like syntax"],
    weaknesses: ["Not transferable outside Godot", "Performance below C# for heavy tasks"],
    bestFor: ["godot projects", "learning programming", "rapid prototyping"],
    tags: ["godot", "beginner-friendly", "scripting", "python-like"],
  },
  // ART
  {
    name: "Aseprite",
    category: "art",
    description: "The industry-standard pixel art and animation tool for game developers. Tilemaps, spritesheet export, frame-by-frame animation.",
    website: "https://aseprite.org",
    pricing: "paid",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Purpose-built for pixel art", "Excellent animation workflow", "Tilemap support", "Sprite sheet export", "Affordable one-time price"],
    weaknesses: ["Pixel art only (no vector or raster painting)", "Niche tool", "One-time purchase (~$20)"],
    bestFor: ["pixel art games", "indie games", "retro aesthetics", "sprite animation"],
    tags: ["pixel-art", "2d", "animation", "sprites", "tiles"],
  },
  {
    name: "Blender",
    category: "art",
    description: "Free open-source 3D modeling, rigging, animation, and rendering suite. Used by indie studios worldwide for game assets.",
    website: "https://blender.org",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Completely free", "Full 3D pipeline (model, rig, animate, render)", "Strong community", "Game asset export (FBX, GLTF)", "Continuous improvements"],
    weaknesses: ["Steep learning curve", "Not optimized for game-real-time workflows", "Can be slow for very large assets"],
    bestFor: ["3d game assets", "character modeling", "environment art", "animations"],
    tags: ["3d", "modeling", "animation", "free", "open-source"],
  },
  {
    name: "Adobe Photoshop",
    category: "art",
    description: "Industry-standard raster image editor. Used for texture creation, UI assets, concept art, and post-processing.",
    website: "https://adobe.com/photoshop",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Industry standard", "Extensive features", "Great for textures and UI", "PSD file compatibility everywhere"],
    weaknesses: ["Expensive subscription", "Heavy software", "Overkill for pixel art", "Not 3D"],
    bestFor: ["texture creation", "UI art", "concept art", "professional studios"],
    tags: ["2d", "textures", "ui", "professional", "adobe"],
  },
  {
    name: "Krita",
    category: "art",
    description: "Free open-source digital painting application. Great for concept art, textures, and 2D game art with a professional brush engine.",
    website: "https://krita.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Free and open source", "Excellent brush engine", "Good for concept art and textures", "Animation support"],
    weaknesses: ["Less industry recognition than Photoshop", "Fewer plugins", "UI can feel dated"],
    bestFor: ["concept art", "2d art", "textures", "budget-conscious teams"],
    tags: ["2d", "painting", "concept-art", "free", "open-source"],
  },
  // ANIMATION
  {
    name: "Spine",
    category: "animation",
    description: "Professional 2D skeletal animation tool widely used in game development. Runtime available for Unity, Godot, and more.",
    website: "http://esotericsoftware.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Industry standard 2D skeletal animation", "Runtime available for major engines", "Powerful mesh deformation", "Smooth animations with small file sizes"],
    weaknesses: ["Significant cost (~$100-300)", "Learning curve for advanced features", "Runtime integrations require setup"],
    bestFor: ["2d character animation", "mobile games", "action games"],
    tags: ["2d", "skeletal-animation", "mobile", "character"],
  },
  {
    name: "DragonBones",
    category: "animation",
    description: "Free 2D skeletal animation tool similar to Spine. Good for mobile game character animation with engine integrations.",
    website: "http://dragonbones.com",
    pricing: "free",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Free alternative to Spine", "Good engine integrations", "Active development"],
    weaknesses: ["Less community support than Spine", "Fewer tutorials", "Documentation quality varies"],
    bestFor: ["2d animation", "budget projects", "mobile games"],
    tags: ["2d", "skeletal-animation", "free", "mobile"],
  },
  // UI / HUD
  {
    name: "Unity UI Toolkit",
    category: "ui",
    description: "Unity's modern UI system using UXML/USS (similar to HTML/CSS). Best for complex, scalable game UI and tooling.",
    website: "https://unity.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console"],
    strengths: ["Modern declarative UI", "CSS-like styling", "Good for complex UI", "Editor tool UI built with it too"],
    weaknesses: ["Newer system with some gaps", "Learning curve for traditional game devs", "3D world-space UI needs workarounds"],
    bestFor: ["complex game ui", "menus", "hud systems", "unity projects"],
    tags: ["ui", "unity", "declarative", "css-like"],
  },
  {
    name: "Godot Control Nodes",
    category: "ui",
    description: "Godot's built-in UI system using Control nodes in the scene tree. Straightforward, integrated with everything Godot.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Deeply integrated with Godot", "Theme system", "Responsive layout", "Easy to learn"],
    weaknesses: ["Godot-only", "Less powerful than web-based UI solutions"],
    bestFor: ["godot projects", "menus", "hud", "game ui"],
    tags: ["ui", "godot", "beginner-friendly"],
  },
  // VFX
  {
    name: "Unity VFX Graph",
    category: "vfx",
    description: "Node-based visual effects editor for Unity's High Definition and Universal Render Pipelines. GPU-accelerated particle systems.",
    website: "https://unity.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "console"],
    strengths: ["GPU-accelerated", "Node-based (no code)", "Extremely powerful", "Integrates with Unity render pipelines"],
    weaknesses: ["Requires HDRP or URP", "Not mobile-friendly", "Steep learning curve", "Heavy GPU requirements"],
    bestFor: ["3d vfx", "realistic effects", "aaa-style games", "pc/console"],
    tags: ["vfx", "particles", "unity", "gpu", "node-based"],
  },
  {
    name: "Godot Particles",
    category: "vfx",
    description: "Godot's built-in particle system for 2D and 3D effects. CPU and GPU modes available, integrated with Godot's scene system.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Built into Godot", "Easy to use", "CPU and GPU modes", "Good for indie games"],
    weaknesses: ["Less powerful than Unity VFX Graph", "Limited shader customization"],
    bestFor: ["2d vfx", "indie game effects", "godot projects"],
    tags: ["vfx", "particles", "godot", "2d"],
  },
  {
    name: "After Effects",
    category: "vfx",
    description: "Adobe's motion graphics and compositing tool. Used for cinematic cutscene VFX and UI animations. Not real-time but exports to sprite sheets.",
    website: "https://adobe.com/after-effects",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Industry-standard motion graphics", "Sprite sheet export plugins", "Huge tutorial library"],
    weaknesses: ["Not real-time", "Expensive subscription", "Requires export to use in engine"],
    bestFor: ["cutscenes", "ui animations", "marketing material", "sprite sheet vfx"],
    tags: ["vfx", "motion-graphics", "2d", "adobe", "cinematic"],
  },
  // VERSION CONTROL
  {
    name: "Git + GitHub",
    category: "version_control",
    description: "The standard version control system for code. GitHub provides hosting, pull requests, and CI/CD integrations.",
    website: "https://github.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Industry standard", "Free for small teams", "Massive ecosystem", "Great for code", "GitHub Actions CI/CD"],
    weaknesses: ["Poor at handling large binary files (art, audio)", "Need Git LFS for binaries (extra cost)", "Command line can be daunting for beginners"],
    bestFor: ["code versioning", "solo projects", "small teams", "open source"],
    tags: ["version-control", "git", "collaboration", "ci-cd"],
  },
  {
    name: "Plastic SCM (Unity DevOps)",
    category: "version_control",
    description: "Version control designed for game development with large binary file support. Now integrated into Unity DevOps.",
    website: "https://unity.com/products/plastic-scm",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Handles large binary files natively", "Good GUI", "Designed for game teams", "Branch and merge for artists"],
    weaknesses: ["Learning curve", "Cost at scale", "Unity ecosystem only effectively"],
    bestFor: ["unity projects", "teams with artists", "large binary assets"],
    tags: ["version-control", "unity", "binary-files", "teams"],
  },
  // DEPLOYMENT
  {
    name: "Steam",
    category: "deployment",
    description: "The dominant PC gaming platform by Valve. Required for most commercial PC game releases. Steamworks SDK for DRM, achievements, leaderboards.",
    website: "https://store.steampowered.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Largest PC gaming marketplace", "Built-in community features", "Sales events driving huge revenue", "Workshop modding support"],
    weaknesses: ["$100 one-time fee per game", "30% revenue cut", "Discovery can be difficult", "Review process required"],
    bestFor: ["pc games", "commercial releases", "indie games"],
    tags: ["deployment", "pc", "commercial", "marketplace"],
  },
  {
    name: "itch.io",
    category: "deployment",
    description: "Open indie game marketplace. Zero upfront cost, flexible revenue sharing, excellent for game jams and indie releases.",
    website: "https://itch.io",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["pc", "web"],
    strengths: ["Free to publish", "Flexible pricing (even free)", "Great game jam community", "Supports pay-what-you-want", "Web game hosting"],
    weaknesses: ["Smaller audience than Steam", "Less discovery infrastructure", "No built-in DRM"],
    bestFor: ["game jams", "free games", "indie experiments", "web games", "demo releases"],
    tags: ["deployment", "indie", "free", "game-jam", "web"],
  },
  {
    name: "Google Play Store",
    category: "deployment",
    description: "Android's primary app and game marketplace. Required for commercial Android game distribution.",
    website: "https://play.google.com/console",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["mobile"],
    strengths: ["2.5B Android users", "Lower entry barrier than Apple", "$25 one-time fee", "Easier sideloading"],
    weaknesses: ["30% revenue cut (reduces to 15% over $1M)", "Review process", "Fragmented Android devices", "More piracy than iOS"],
    bestFor: ["android games", "mobile games", "free-to-play"],
    tags: ["deployment", "android", "mobile", "commercial"],
  },
  {
    name: "Apple App Store",
    category: "deployment",
    description: "iOS and macOS app marketplace. Required for commercial iOS game distribution. Strict review process.",
    website: "https://developer.apple.com",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["mobile"],
    strengths: ["High-spending user base", "Better security reputation", "Mac + iOS unified distribution", "Good discovery algorithms"],
    weaknesses: ["$99/year developer fee", "Strict review guidelines", "30% revenue cut", "Requires Mac for builds"],
    bestFor: ["ios games", "premium mobile games", "high-revenue mobile"],
    tags: ["deployment", "ios", "mobile", "apple"],
  },
  // AI TOOLING
  {
    name: "GitHub Copilot",
    category: "ai_tooling",
    description: "AI pair programmer integrated into VS Code, Visual Studio, JetBrains IDEs. Autocompletes code, suggests implementations, writes tests.",
    website: "https://github.com/features/copilot",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Excellent code autocomplete", "Works in your existing IDE", "Speeds up boilerplate", "Good at explaining code"],
    weaknesses: ["Monthly subscription cost", "Can suggest incorrect code", "Privacy concerns", "Less useful for engine-specific patterns"],
    bestFor: ["code generation", "all skill levels", "script writing", "productivity"],
    tags: ["ai", "code-generation", "ide", "productivity"],
  },
  {
    name: "Midjourney",
    category: "ai_tooling",
    description: "AI image generation tool via Discord. Produces high-quality concept art, textures, and visual references for game development.",
    website: "https://midjourney.com",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Extremely high quality output", "Fast concept generation", "Great for visual references", "Consistent art styles"],
    weaknesses: ["Subscription required", "Discord-based UI is awkward", "Commercial license terms vary", "Not pixel art focused"],
    bestFor: ["concept art", "texture references", "art direction", "prototyping visuals"],
    tags: ["ai", "art-generation", "concept-art", "textures"],
  },
  {
    name: "ChatGPT / GPT-4",
    category: "ai_tooling",
    description: "General-purpose AI assistant by OpenAI. Useful for game design brainstorming, dialog writing, game mechanics analysis, and code debugging.",
    website: "https://chat.openai.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Versatile: design, writing, code, analysis", "Free tier available", "Good at game design consulting", "Explains complex concepts"],
    weaknesses: ["Not game-engine specific", "Can hallucinate API details", "Requires good prompting"],
    bestFor: ["game design", "dialog writing", "brainstorming", "code help", "documentation"],
    tags: ["ai", "writing", "design", "brainstorming", "code-help"],
  },
];

export const TOOL_CATEGORIES = [
  { id: "engine", label: "Game Engine", description: "Core engine powering your game's rendering, physics, and scene management" },
  { id: "programming", label: "Programming Language", description: "Primary scripting and programming language for game logic" },
  { id: "art", label: "Art & Assets", description: "Tools for creating 2D/3D art, textures, and visual assets" },
  { id: "animation", label: "Animation", description: "Character and object animation tools" },
  { id: "ui", label: "UI / HUD", description: "User interface and heads-up display systems" },
  { id: "vfx", label: "VFX & Particles", description: "Visual effects, particle systems, and post-processing" },
  { id: "version_control", label: "Version Control", description: "Source control and collaboration for code and assets" },
  { id: "deployment", label: "Deployment & Distribution", description: "Platforms and stores for publishing your game" },
  { id: "ai_tooling", label: "AI Tooling", description: "AI-powered tools for accelerating development" },
];
