export interface GameDevTool {
  name: string;
  category: string;
  description: string;
  website: string;
  pricing: "free" | "freemium" | "paid" | "subscription" | "open_source";
  minSkillLevel: "beginner" | "intermediate" | "advanced" | "expert";
  platforms: string[];
  strengths: string[];
  weaknesses: string[];
  bestFor: string[];
  tags: string[];
}

export const GAME_DEV_TOOLS: GameDevTool[] = [
  // ENGINE
  {
    name: "Unity",
    category: "engine",
    description: "The world's most popular cross-platform game engine, used for 2D, 3D, VR, and AR games. C# scripting, massive asset store, excellent beginner support.",
    website: "https://unity.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "console", "vr"],
    strengths: ["Massive community & tutorials", "Huge Asset Store", "Excellent cross-platform support", "Strong 2D and 3D pipeline", "Visual scripting available"],
    weaknesses: ["Performance overhead vs native engines", "Licensing costs at scale", "Complex build pipeline", "Runtime fee controversy"],
    bestFor: ["mobile games", "indie games", "prototypes", "VR/AR", "cross-platform releases"],
    tags: ["2d", "3d", "mobile", "vr", "ar", "beginner-friendly", "c#"],
  },
  {
    name: "Unreal Engine",
    category: "engine",
    description: "AAA-quality 3D game engine by Epic Games. Industry standard for realistic graphics, large-scale games, and cinematics. Blueprints + C++ workflow.",
    website: "https://unrealengine.com",
    pricing: "free",
    minSkillLevel: "intermediate",
    platforms: ["pc", "console", "mobile", "vr"],
    strengths: ["Photorealistic graphics out of the box", "Nanite & Lumen rendering", "Blueprint visual scripting", "Free until $1M revenue", "AAA studio standard"],
    weaknesses: ["Steep learning curve", "Heavy resource requirements", "Complex project setup", "Overkill for simple 2D games", "Longer compile times"],
    bestFor: ["3d games", "realistic graphics", "shooters", "open world", "VR", "cinematics"],
    tags: ["3d", "aaa", "blueprints", "c++", "realistic", "console", "vr"],
  },
  {
    name: "Godot",
    category: "engine",
    description: "Free and open-source game engine with GDScript (Python-like) and C# support. Lightweight, excellent for 2D games, rapidly improving 3D pipeline.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "console"],
    strengths: ["Completely free & open source", "Lightweight & fast", "Excellent 2D pipeline", "Python-like GDScript easy to learn", "No revenue royalties ever"],
    weaknesses: ["3D still maturing vs Unity/Unreal", "Smaller community", "Fewer third-party assets", "Limited console support (needs platform SDK)"],
    bestFor: ["2d games", "indie games", "game jams", "open source projects", "learning game dev"],
    tags: ["2d", "3d", "open-source", "free", "beginner-friendly", "gdscript"],
  },
  {
    name: "GameMaker",
    category: "engine",
    description: "Specialized 2D game engine with GML scripting. Used to make classics like Undertale and Hotline Miami. Fast prototyping, beginner-friendly.",
    website: "https://gamemaker.io",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "console"],
    strengths: ["Purpose-built for 2D", "GML is easy to learn", "Fast iteration", "Proven for commercial 2D hits", "Good export options"],
    weaknesses: ["Not suited for 3D", "Subscription required for commercial use", "Less flexibility than general engines", "GML not transferable"],
    bestFor: ["2d games", "pixel art games", "game jams", "retro games", "platformers"],
    tags: ["2d", "pixel-art", "beginner-friendly", "gml", "retro"],
  },
  {
    name: "Phaser",
    category: "engine",
    description: "HTML5 game framework for browser-based 2D games using JavaScript/TypeScript. Excellent for web-native games and game jams.",
    website: "https://phaser.io",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["web"],
    strengths: ["Native web platform", "JavaScript/TypeScript", "No install required for players", "Great for web monetization", "Strong browser performance"],
    weaknesses: ["Web-only (no native mobile/desktop)", "JavaScript can be slow vs native", "Limited 3D support", "No visual editor"],
    bestFor: ["browser games", "web monetization", "web game jams", "html5 games"],
    tags: ["web", "html5", "javascript", "typescript", "2d", "browser"],
  },
  {
    name: "Cocos Creator",
    category: "engine",
    description: "Open-source engine focused on 2D and lightweight 3D with a component workflow and TypeScript scripting. Popular for mobile and web games, especially in Asia.",
    website: "https://www.cocos.com/en/creator",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web", "cross-platform"],
    strengths: ["Strong mobile performance", "TypeScript-first workflow", "Good 2D tooling", "Open-source core"],
    weaknesses: ["Smaller Western community", "Less AAA 3D tooling", "Plugin ecosystem smaller than Unity"],
    bestFor: ["mobile games", "2d games", "web exports", "performance-focused projects"],
    tags: ["2d", "3d", "mobile", "web", "typescript", "open-source"],
  },
  {
    name: "Defold",
    category: "engine",
    description: "Lightweight free engine with Lua scripting and strong 2D capabilities. Uses a component-based architecture and supports native, web, and mobile exports.",
    website: "https://defold.com",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "cross-platform"],
    strengths: ["Fast iteration", "Small runtime footprint", "Friendly editor", "No royalties"],
    weaknesses: ["Smaller asset ecosystem", "Limited high-end 3D workflows", "Fewer third-party tutorials"],
    bestFor: ["2d games", "mobile games", "indie projects", "game jams"],
    tags: ["2d", "lua", "mobile", "web", "game-jam", "beginner-friendly"],
  },
  {
    name: "LOVE",
    category: "engine",
    description: "Minimal open-source 2D framework using Lua. Code-first approach with a very fast feedback loop and excellent fit for prototyping and game jams.",
    website: "https://love2d.org",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Very lightweight", "Simple Lua API", "Great for rapid prototyping", "Strong jam community"],
    weaknesses: ["No built-in visual editor", "Framework-level tooling", "2D-focused only"],
    bestFor: ["2d prototypes", "game jams", "retro projects", "code-first workflows"],
    tags: ["2d", "lua", "open-source", "game-jam", "retro"],
  },
  {
    name: "Construct 3",
    category: "engine",
    description: "Browser-based no-code/low-code 2D game engine with event-sheet scripting. Fast onboarding for non-programmers and educators with web-first deployment.",
    website: "https://www.construct.net",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["web", "mobile", "pc"],
    strengths: ["Very beginner-friendly", "No-code event system", "Runs in browser", "Fast 2D prototyping"],
    weaknesses: ["Subscription cost", "Limited for complex architecture", "Less flexibility than code-heavy engines"],
    bestFor: ["beginner projects", "education", "2d games", "web games"],
    tags: ["2d", "beginner-friendly", "web", "rapid-prototyping"],
  },
  {
    name: "Bevy",
    category: "engine",
    description: "Modern open-source Rust game engine built around ECS architecture. High performance and strong systems-level control for teams comfortable with Rust.",
    website: "https://bevyengine.org",
    pricing: "open_source",
    minSkillLevel: "advanced",
    platforms: ["pc", "web", "mobile", "cross-platform"],
    strengths: ["High performance ECS", "Rust safety guarantees", "Modern architecture", "Open-source community"],
    weaknesses: ["Young ecosystem", "Steeper learning curve", "Tooling still maturing"],
    bestFor: ["performance-critical games", "rust projects", "engine programmers", "experimental systems"],
    tags: ["3d", "2d", "rust", "ecs", "open-source"],
  },
  // PROGRAMMING
  {
    name: "C# with .NET",
    category: "programming",
    description: "Primary scripting language for Unity. Strongly typed, modern OOP, excellent IDE tooling with Visual Studio or Rider.",
    website: "https://dotnet.microsoft.com",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web", "console"],
    strengths: ["Strongly typed reduces bugs", "Excellent IDE support", "Great performance", "Async/await built-in", "Rich ecosystem"],
    weaknesses: ["Steeper learning curve than GDScript", "Not directly portable outside Unity context"],
    bestFor: ["unity development", "large teams", "complex game systems"],
    tags: ["unity", "oop", "strongly-typed", "c#"],
  },
  {
    name: "GDScript",
    category: "programming",
    description: "Python-inspired scripting language native to Godot. Easy to learn, tightly integrated with the Godot editor and scene system.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Very easy to learn", "Deep Godot integration", "Fast iteration", "Clean Python-like syntax"],
    weaknesses: ["Not transferable outside Godot", "Performance below C# for heavy tasks"],
    bestFor: ["godot projects", "learning programming", "rapid prototyping"],
    tags: ["godot", "beginner-friendly", "scripting", "python-like"],
  },
  {
    name: "C++",
    category: "programming",
    description: "Low-level high-performance language used heavily in Unreal Engine and custom engine development. Offers deep control over memory and runtime behavior.",
    website: "https://isocpp.org",
    pricing: "open_source",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Top-tier performance", "Fine-grained control", "Industry standard for AAA", "Large ecosystem"],
    weaknesses: ["Complex syntax", "Manual memory pitfalls", "Longer iteration times"],
    bestFor: ["unreal development", "engine programming", "performance-critical gameplay"],
    tags: ["c++", "performance", "aaa", "systems"],
  },
  {
    name: "Lua",
    category: "programming",
    description: "Lightweight embeddable scripting language common in game engines and tooling. Easy to integrate and fast for iteration-heavy gameplay scripting.",
    website: "https://www.lua.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "cross-platform"],
    strengths: ["Small and fast", "Easy syntax", "Great for embedded scripting", "Proven in game stacks"],
    weaknesses: ["Limited static typing", "Smaller general ecosystem than JS/Python"],
    bestFor: ["scripting gameplay", "embedded tools", "rapid iteration"],
    tags: ["lua", "scripting", "beginner-friendly", "game-jam"],
  },
  {
    name: "JavaScript / TypeScript",
    category: "programming",
    description: "Primary language pair for web game development and many modern tooling pipelines. TypeScript adds static typing for larger codebases.",
    website: "https://www.typescriptlang.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["web", "pc", "mobile", "cross-platform"],
    strengths: ["Huge ecosystem", "Excellent web support", "Fast tooling", "TypeScript improves maintainability"],
    weaknesses: ["Runtime performance limits", "Package ecosystem churn", "Browser compatibility concerns"],
    bestFor: ["web games", "tools", "live-ops dashboards", "cross-platform frontends"],
    tags: ["javascript", "typescript", "web", "tooling", "beginner-friendly"],
  },
  {
    name: "Rust",
    category: "programming",
    description: "Systems language emphasizing memory safety and performance without garbage collection. Growing adoption in game engines and backend services.",
    website: "https://www.rust-lang.org",
    pricing: "open_source",
    minSkillLevel: "advanced",
    platforms: ["pc", "web", "mobile", "console", "cross-platform"],
    strengths: ["Memory safety", "High performance", "Strong compiler tooling", "Good for concurrent systems"],
    weaknesses: ["Steep learning curve", "Long compile times", "Smaller game middleware ecosystem"],
    bestFor: ["engine systems", "performance-critical code", "backend services"],
    tags: ["rust", "performance", "systems", "open-source"],
  },
  {
    name: "Haxe",
    category: "programming",
    description: "Cross-platform language that compiles to multiple targets including C++, JavaScript, and C#. Historically strong in 2D and web game workflows.",
    website: "https://haxe.org",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "web", "mobile", "console", "cross-platform"],
    strengths: ["Multi-target compilation", "Strong for cross-platform code reuse", "Mature in indie ecosystems"],
    weaknesses: ["Smaller talent pool", "Niche ecosystem", "Less mainstream tooling"],
    bestFor: ["cross-platform 2d games", "shared game logic", "indie pipelines"],
    tags: ["haxe", "cross-platform", "2d", "open-source"],
  },
  {
    name: "Python",
    category: "programming",
    description: "General-purpose language used in game tooling, automation, build scripts, and pipeline integration. Also common for AI tooling around game development.",
    website: "https://www.python.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "web", "cross-platform"],
    strengths: ["Very readable syntax", "Huge libraries", "Great automation language", "Strong AI ecosystem"],
    weaknesses: ["Not ideal for runtime performance", "Packaging complexity at scale"],
    bestFor: ["tooling scripts", "content pipelines", "automation", "ai workflows"],
    tags: ["python", "tooling", "ai", "automation", "beginner-friendly"],
  },
  // ART
  {
    name: "Aseprite",
    category: "art",
    description: "The industry-standard pixel art and animation tool for game developers. Tilemaps, spritesheet export, frame-by-frame animation.",
    website: "https://aseprite.org",
    pricing: "paid",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Purpose-built for pixel art", "Excellent animation workflow", "Tilemap support", "Sprite sheet export", "Affordable one-time price"],
    weaknesses: ["Pixel art only (no vector or raster painting)", "Niche tool", "One-time purchase (~$20)"],
    bestFor: ["pixel art games", "indie games", "retro aesthetics", "sprite animation"],
    tags: ["pixel-art", "2d", "animation", "sprites", "tiles"],
  },
  {
    name: "Blender",
    category: "art",
    description: "Free open-source 3D modeling, rigging, animation, and rendering suite. Used by indie studios worldwide for game assets.",
    website: "https://blender.org",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Completely free", "Full 3D pipeline (model, rig, animate, render)", "Strong community", "Game asset export (FBX, GLTF)", "Continuous improvements"],
    weaknesses: ["Steep learning curve", "Not optimized for game-real-time workflows", "Can be slow for very large assets"],
    bestFor: ["3d game assets", "character modeling", "environment art", "animations"],
    tags: ["3d", "modeling", "animation", "free", "open-source"],
  },
  {
    name: "Adobe Photoshop",
    category: "art",
    description: "Industry-standard raster image editor. Used for texture creation, UI assets, concept art, and post-processing.",
    website: "https://adobe.com/photoshop",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Industry standard", "Extensive features", "Great for textures and UI", "PSD file compatibility everywhere"],
    weaknesses: ["Expensive subscription", "Heavy software", "Overkill for pixel art", "Not 3D"],
    bestFor: ["texture creation", "UI art", "concept art", "professional studios"],
    tags: ["2d", "textures", "ui", "professional", "adobe"],
  },
  {
    name: "Krita",
    category: "art",
    description: "Free open-source digital painting application. Great for concept art, textures, and 2D game art with a professional brush engine.",
    website: "https://krita.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Free and open source", "Excellent brush engine", "Good for concept art and textures", "Animation support"],
    weaknesses: ["Less industry recognition than Photoshop", "Fewer plugins", "UI can feel dated"],
    bestFor: ["concept art", "2d art", "textures", "budget-conscious teams"],
    tags: ["2d", "painting", "concept-art", "free", "open-source"],
  },
  {
    name: "Substance Painter",
    category: "art",
    description: "Industry-standard texture painting suite for PBR materials on 3D assets. Offers real-time viewport feedback and exports tuned for major engines.",
    website: "https://www.adobe.com/products/substance3d-painter.html",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Excellent PBR workflow", "Smart masks and materials", "Strong engine export presets"],
    weaknesses: ["Subscription/license cost", "Focused on texturing only", "Requires solid UV workflow"],
    bestFor: ["3d texturing", "character assets", "environment materials"],
    tags: ["3d", "textures", "pbr", "professional"],
  },
  {
    name: "Substance Designer",
    category: "art",
    description: "Node-based procedural material authoring tool for creating reusable PBR materials. Widely used in production pipelines for scalable asset generation.",
    website: "https://www.adobe.com/products/substance3d-designer.html",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Procedural reusable materials", "Powerful node workflows", "Pipeline-friendly outputs"],
    weaknesses: ["Steep learning curve", "Best value in larger pipelines", "Subscription cost"],
    bestFor: ["material libraries", "environment production", "technical art workflows"],
    tags: ["3d", "materials", "node-based", "technical-art"],
  },
  {
    name: "ZBrush",
    category: "art",
    description: "Digital sculpting package used for high-detail character and creature creation. Commonly used to produce high-poly sculpts for bake-down game assets.",
    website: "https://www.maxon.net/zbrush",
    pricing: "paid",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Best-in-class sculpting", "Handles dense meshes", "Production-proven character pipeline"],
    weaknesses: ["Unique UI paradigm", "Steep learning curve", "Requires retopo/baking workflow"],
    bestFor: ["character sculpting", "creatures", "high-poly concept meshes"],
    tags: ["3d", "sculpting", "character-art", "advanced"],
  },
  {
    name: "Autodesk Maya",
    category: "art",
    description: "Comprehensive DCC suite for 3D modeling, rigging, and pipeline integration. Widely used in AAA and studio production environments.",
    website: "https://www.autodesk.com/products/maya",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Studio-standard pipeline tool", "Strong rigging and modeling", "Deep scripting support"],
    weaknesses: ["High subscription cost", "Steep learning curve", "Heavy software footprint"],
    bestFor: ["aaa pipelines", "character production", "team-based 3d workflows"],
    tags: ["3d", "modeling", "rigging", "professional", "aaa"],
  },
  {
    name: "Procreate",
    category: "art",
    description: "iPad-first digital painting app popular for concept sketches, UI mockups, and stylized 2D art ideation. Fast and intuitive for portable workflows.",
    website: "https://procreate.com",
    pricing: "paid",
    minSkillLevel: "beginner",
    platforms: ["mobile"],
    strengths: ["Very approachable UX", "Strong brush engine", "Great for ideation on the go"],
    weaknesses: ["iPad-only", "Not a full pipeline suite", "Limited advanced production tooling"],
    bestFor: ["concept sketches", "2d ideation", "art direction drafts"],
    tags: ["2d", "painting", "concept-art", "beginner-friendly"],
  },
  {
    name: "Pyxel Edit",
    category: "art",
    description: "Tile-focused pixel art editor built for fast environment and tileset creation. Popular in retro and top-down indie projects.",
    website: "https://pyxeledit.com",
    pricing: "paid",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Great tilemap workflow", "Simple focused UI", "Good for environment art"],
    weaknesses: ["Narrow scope vs Aseprite", "Smaller community", "Limited non-pixel use"],
    bestFor: ["tilemap production", "pixel environments", "retro projects"],
    tags: ["pixel-art", "2d", "tiles", "retro", "beginner-friendly"],
  },
  // ANIMATION
  {
    name: "Spine",
    category: "animation",
    description: "Professional 2D skeletal animation tool widely used in game development. Runtime available for Unity, Godot, and more.",
    website: "http://esotericsoftware.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Industry standard 2D skeletal animation", "Runtime available for major engines", "Powerful mesh deformation", "Smooth animations with small file sizes"],
    weaknesses: ["Significant cost (~$100-300)", "Learning curve for advanced features", "Runtime integrations require setup"],
    bestFor: ["2d character animation", "mobile games", "action games"],
    tags: ["2d", "skeletal-animation", "mobile", "character"],
  },
  {
    name: "DragonBones",
    category: "animation",
    description: "Free 2D skeletal animation tool similar to Spine. Good for mobile game character animation with engine integrations.",
    website: "http://dragonbones.com",
    pricing: "free",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Free alternative to Spine", "Good engine integrations", "Active development"],
    weaknesses: ["Less community support than Spine", "Fewer tutorials", "Documentation quality varies"],
    bestFor: ["2d animation", "budget projects", "mobile games"],
    tags: ["2d", "skeletal-animation", "free", "mobile"],
  },
  {
    name: "Cascadeur",
    category: "animation",
    description: "3D keyframe animation software with physics-assisted posing and auto-physics features. Useful for more natural character motion without full mocap sessions.",
    website: "https://cascadeur.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Physics-assisted posing", "Good for action animation", "Indie-accessible pricing"],
    weaknesses: ["Narrow focus vs full DCC tools", "Pipeline integration setup required"],
    bestFor: ["character animation", "combat moves", "indie 3d projects"],
    tags: ["3d", "character", "physics", "animation"],
  },
  {
    name: "Mixamo",
    category: "animation",
    description: "Adobe service for automatic character rigging and a large library of mocap animations. Speeds up prototyping and placeholder animation work.",
    website: "https://www.mixamo.com",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Fast auto-rigging", "Large animation library", "Great prototyping speed"],
    weaknesses: ["Generic motion style", "Limited deep customization", "External workflow step"],
    bestFor: ["prototype animation", "indie teams", "placeholder character motion"],
    tags: ["3d", "mocap", "character", "beginner-friendly"],
  },
  {
    name: "Live2D Cubism",
    category: "animation",
    description: "2D mesh deformation and rigging system used for anime-style character motion. Common in visual novels, mobile RPGs, and VTuber-adjacent workflows.",
    website: "https://www.live2d.com/en/cubism",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web"],
    strengths: ["High-quality 2D character motion", "Efficient runtime output", "Strong stylized character support"],
    weaknesses: ["Specialized workflow", "License cost", "Learning curve for rig structure"],
    bestFor: ["visual novels", "anime-style characters", "mobile rpg ui characters"],
    tags: ["2d", "character", "rigging", "mobile"],
  },
  {
    name: "Maya Animation",
    category: "animation",
    description: "Maya's professional animation toolset for rigging, keyframing, and cinematic character workflows. Standard in many studio animation pipelines.",
    website: "https://www.autodesk.com/products/maya",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Production-proven pipeline", "Deep rigging tools", "Strong cinematic support"],
    weaknesses: ["High cost", "Steep onboarding", "Complex setup for solo creators"],
    bestFor: ["studio pipelines", "character animation", "cinematic sequences"],
    tags: ["3d", "animation", "rigging", "professional", "aaa"],
  },
  // UI / HUD
  {
    name: "Unity UI Toolkit",
    category: "ui",
    description: "Unity's modern UI system using UXML/USS (similar to HTML/CSS). Best for complex, scalable game UI and tooling.",
    website: "https://unity.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console"],
    strengths: ["Modern declarative UI", "CSS-like styling", "Good for complex UI", "Editor tool UI built with it too"],
    weaknesses: ["Newer system with some gaps", "Learning curve for traditional game devs", "3D world-space UI needs workarounds"],
    bestFor: ["complex game ui", "menus", "hud systems", "unity projects"],
    tags: ["ui", "unity", "declarative", "css-like"],
  },
  {
    name: "Godot Control Nodes",
    category: "ui",
    description: "Godot's built-in UI system using Control nodes in the scene tree. Straightforward, integrated with everything Godot.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Deeply integrated with Godot", "Theme system", "Responsive layout", "Easy to learn"],
    weaknesses: ["Godot-only", "Less powerful than web-based UI solutions"],
    bestFor: ["godot projects", "menus", "hud", "game ui"],
    tags: ["ui", "godot", "beginner-friendly"],
  },
  {
    name: "NoesisGUI",
    category: "ui",
    description: "XAML-based retained-mode UI middleware for games with strong runtime performance and tooling. Used when teams want scalable app-like UI patterns in games.",
    website: "https://www.noesisengine.com",
    pricing: "paid",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["High-performance runtime UI", "Powerful data binding", "Scalable for complex HUD/menu systems"],
    weaknesses: ["License cost", "Advanced setup", "Smaller community than engine-native UI"],
    bestFor: ["complex hud", "cross-platform ui", "studio ui architecture"],
    tags: ["ui", "hud", "cross-platform", "realtime"],
  },
  {
    name: "Rive",
    category: "ui",
    description: "Real-time interactive animation and UI tool for runtime motion graphics. Useful for polished menus, onboarding flows, and animated HUD elements.",
    website: "https://rive.app",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["web", "mobile", "pc", "cross-platform"],
    strengths: ["Interactive runtime animation", "Compact vector-based assets", "Good cross-platform runtimes"],
    weaknesses: ["Extra integration step", "Advanced states require planning"],
    bestFor: ["animated ui", "polished menus", "interactive hud elements"],
    tags: ["ui", "animation", "realtime", "cross-platform"],
  },
  // VFX
  {
    name: "Unity VFX Graph",
    category: "vfx",
    description: "Node-based visual effects editor for Unity's High Definition and Universal Render Pipelines. GPU-accelerated particle systems.",
    website: "https://unity.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "console"],
    strengths: ["GPU-accelerated", "Node-based (no code)", "Extremely powerful", "Integrates with Unity render pipelines"],
    weaknesses: ["Requires HDRP or URP", "Not mobile-friendly", "Steep learning curve", "Heavy GPU requirements"],
    bestFor: ["3d vfx", "realistic effects", "aaa-style games", "pc/console"],
    tags: ["vfx", "particles", "unity", "gpu", "node-based"],
  },
  {
    name: "Godot Particles",
    category: "vfx",
    description: "Godot's built-in particle system for 2D and 3D effects. CPU and GPU modes available, integrated with Godot's scene system.",
    website: "https://godotengine.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web"],
    strengths: ["Built into Godot", "Easy to use", "CPU and GPU modes", "Good for indie games"],
    weaknesses: ["Less powerful than Unity VFX Graph", "Limited shader customization"],
    bestFor: ["2d vfx", "indie game effects", "godot projects"],
    tags: ["vfx", "particles", "godot", "2d"],
  },
  {
    name: "After Effects",
    category: "vfx",
    description: "Adobe's motion graphics and compositing tool. Used for cinematic cutscene VFX and UI animations. Not real-time but exports to sprite sheets.",
    website: "https://adobe.com/after-effects",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Industry-standard motion graphics", "Sprite sheet export plugins", "Huge tutorial library"],
    weaknesses: ["Not real-time", "Expensive subscription", "Requires export to use in engine"],
    bestFor: ["cutscenes", "ui animations", "marketing material", "sprite sheet vfx"],
    tags: ["vfx", "motion-graphics", "2d", "adobe", "cinematic"],
  },
  {
    name: "Niagara (UE5)",
    category: "vfx",
    description: "Unreal Engine 5's advanced node-based VFX framework for particles, simulations, and gameplay-reactive effects. Built for high-fidelity real-time visuals.",
    website: "https://www.unrealengine.com",
    pricing: "free",
    minSkillLevel: "advanced",
    platforms: ["pc", "console", "mobile", "vr"],
    strengths: ["Deep UE5 integration", "Powerful data-driven effects", "AAA-quality real-time visuals"],
    weaknesses: ["Complex system", "Heavy for simple projects", "UE-focused workflow"],
    bestFor: ["unreal projects", "high-end 3d vfx", "gameplay-reactive particles"],
    tags: ["vfx", "unreal", "niagara", "3d", "realtime", "aaa"],
  },
  {
    name: "Houdini",
    category: "vfx",
    description: "Procedural 3D and VFX suite used for advanced simulations, destruction, and technical art pipelines. Houdini Engine enables integration into game editors.",
    website: "https://www.sidefx.com/products/houdini",
    pricing: "subscription",
    minSkillLevel: "expert",
    platforms: ["pc"],
    strengths: ["Best-in-class procedural workflows", "Advanced simulation tools", "Scales to complex production"],
    weaknesses: ["Very steep learning curve", "High complexity", "Expensive for small teams"],
    bestFor: ["technical art", "procedural worlds", "simulation-heavy pipelines"],
    tags: ["vfx", "procedural", "simulation", "technical-art", "3d"],
  },
  {
    name: "EmberGen",
    category: "vfx",
    description: "Real-time volumetric fluid and smoke simulation tool used to author explosions, fire, and clouds. Exports baked assets for engine use.",
    website: "https://jangafx.com/software/embergen",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Fast real-time iteration", "High-quality volumetrics", "Good export options for games"],
    weaknesses: ["Specialized scope", "Paid license", "Requires integration into engine pipeline"],
    bestFor: ["explosions", "fire and smoke effects", "cinematic vfx assets"],
    tags: ["vfx", "volumetric", "realtime", "3d"],
  },
  // VERSION CONTROL
  {
    name: "Git + GitHub",
    category: "version_control",
    description: "The standard version control system for code. GitHub provides hosting, pull requests, and CI/CD integrations.",
    website: "https://github.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Industry standard", "Free for small teams", "Massive ecosystem", "Great for code", "GitHub Actions CI/CD"],
    weaknesses: ["Poor at handling large binary files (art, audio)", "Need Git LFS for binaries (extra cost)", "Command line can be daunting for beginners"],
    bestFor: ["code versioning", "solo projects", "small teams", "open source"],
    tags: ["version-control", "git", "collaboration", "ci-cd"],
  },
  {
    name: "Plastic SCM (Unity DevOps)",
    category: "version_control",
    description: "Version control designed for game development with large binary file support. Now integrated into Unity DevOps.",
    website: "https://unity.com/products/plastic-scm",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Handles large binary files natively", "Good GUI", "Designed for game teams", "Branch and merge for artists"],
    weaknesses: ["Learning curve", "Cost at scale", "Unity ecosystem only effectively"],
    bestFor: ["unity projects", "teams with artists", "large binary assets"],
    tags: ["version-control", "unity", "binary-files", "teams"],
  },
  {
    name: "Perforce Helix Core",
    category: "version_control",
    description: "Enterprise version control system widely used in AAA game studios for very large binary assets and multi-site collaboration.",
    website: "https://www.perforce.com/products/helix-core",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc", "cross-platform"],
    strengths: ["Excellent large binary handling", "Scales to massive depots", "Strong permissions/workflow controls"],
    weaknesses: ["Operational complexity", "Infrastructure/admin overhead", "Cost at scale"],
    bestFor: ["aaa teams", "large asset repositories", "studio pipelines"],
    tags: ["version-control", "binary-files", "teams", "enterprise"],
  },
  {
    name: "GitLab",
    category: "version_control",
    description: "Git hosting platform with integrated CI/CD, issue tracking, and self-hosting options. Useful for teams needing all-in-one DevOps workflows.",
    website: "https://gitlab.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "cross-platform"],
    strengths: ["Integrated CI/CD", "Self-hosting available", "Strong project management tooling"],
    weaknesses: ["Git binary limitations still apply", "Can be heavy to administer self-hosted"],
    bestFor: ["devops workflows", "self-hosted teams", "code collaboration"],
    tags: ["version-control", "git", "ci-cd", "cloud"],
  },
  {
    name: "Diversion",
    category: "version_control",
    description: "Game-focused source control aimed at artist-friendly binary workflows and simpler collaboration UX than traditional Git setups.",
    website: "https://www.diversion.dev",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Artist-friendly workflow", "Simplified setup", "Built for game assets"],
    weaknesses: ["Newer ecosystem", "Smaller community", "Fewer mature integrations"],
    bestFor: ["small game teams", "binary asset collaboration", "indie production"],
    tags: ["version-control", "binary-files", "beginner-friendly", "collaboration"],
  },
  // DEPLOYMENT
  {
    name: "Steam",
    category: "deployment",
    description: "The dominant PC gaming platform by Valve. Required for most commercial PC game releases. Steamworks SDK for DRM, achievements, leaderboards.",
    website: "https://store.steampowered.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Largest PC gaming marketplace", "Built-in community features", "Sales events driving huge revenue", "Workshop modding support"],
    weaknesses: ["$100 one-time fee per game", "30% revenue cut", "Discovery can be difficult", "Review process required"],
    bestFor: ["pc games", "commercial releases", "indie games"],
    tags: ["deployment", "pc", "commercial", "marketplace"],
  },
  {
    name: "itch.io",
    category: "deployment",
    description: "Open indie game marketplace. Zero upfront cost, flexible revenue sharing, excellent for game jams and indie releases.",
    website: "https://itch.io",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["pc", "web"],
    strengths: ["Free to publish", "Flexible pricing (even free)", "Great game jam community", "Supports pay-what-you-want", "Web game hosting"],
    weaknesses: ["Smaller audience than Steam", "Less discovery infrastructure", "No built-in DRM"],
    bestFor: ["game jams", "free games", "indie experiments", "web games", "demo releases"],
    tags: ["deployment", "indie", "free", "game-jam", "web"],
  },
  {
    name: "Google Play Store",
    category: "deployment",
    description: "Android's primary app and game marketplace. Required for commercial Android game distribution.",
    website: "https://play.google.com/console",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["mobile"],
    strengths: ["2.5B Android users", "Lower entry barrier than Apple", "$25 one-time fee", "Easier sideloading"],
    weaknesses: ["30% revenue cut (reduces to 15% over $1M)", "Review process", "Fragmented Android devices", "More piracy than iOS"],
    bestFor: ["android games", "mobile games", "free-to-play"],
    tags: ["deployment", "android", "mobile", "commercial"],
  },
  {
    name: "Apple App Store",
    category: "deployment",
    description: "iOS and macOS app marketplace. Required for commercial iOS game distribution. Strict review process.",
    website: "https://developer.apple.com",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["mobile"],
    strengths: ["High-spending user base", "Better security reputation", "Mac + iOS unified distribution", "Good discovery algorithms"],
    weaknesses: ["$99/year developer fee", "Strict review guidelines", "30% revenue cut", "Requires Mac for builds"],
    bestFor: ["ios games", "premium mobile games", "high-revenue mobile"],
    tags: ["deployment", "ios", "mobile", "apple"],
  },
  {
    name: "Epic Games Store",
    category: "deployment",
    description: "PC game storefront by Epic with favorable revenue share terms and growing audience. Includes developer portal tooling and store integrations.",
    website: "https://store.epicgames.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Favorable revenue split", "Strong PC audience", "Epic ecosystem integration"],
    weaknesses: ["Smaller audience than Steam", "Curation/release requirements", "Lower discoverability tools"],
    bestFor: ["pc commercial releases", "indie-to-midcore launches", "epic ecosystem titles"],
    tags: ["deployment", "pc", "commercial", "marketplace"],
  },
  {
    name: "GOG Connect / GOG Galaxy",
    category: "deployment",
    description: "GOG distribution ecosystem focused on DRM-free PC releases and community trust. GOG Galaxy provides launcher and user account integration.",
    website: "https://www.gog.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["DRM-free positioning", "Loyal PC audience", "Strong fit for premium titles"],
    weaknesses: ["Smaller install base than Steam", "Selective onboarding", "Fewer live-service features"],
    bestFor: ["premium pc games", "drm-free releases", "catalog distribution"],
    tags: ["deployment", "pc", "commercial", "drm-free"],
  },
  {
    name: "Xbox / PlayStation / Nintendo Partner Portals",
    category: "deployment",
    description: "Official console publishing portals and certification pipelines for Xbox, PlayStation, and Nintendo platforms. Required path for commercial console releases.",
    website: "https://developer.microsoft.com/games",
    pricing: "paid",
    minSkillLevel: "advanced",
    platforms: ["console"],
    strengths: ["Required for console launch", "Access to platform SDK and certification docs", "First-party publishing support"],
    weaknesses: ["Strict certification requirements", "Long lead times", "Higher business/legal overhead"],
    bestFor: ["console launches", "certification workflows", "cross-platform commercial releases"],
    tags: ["deployment", "console", "certification", "commercial"],
  },
  {
    name: "CrazyGames",
    category: "deployment",
    description: "Web game platform for instant-play HTML5 games with built-in distribution and monetization opportunities. Strong for rapid browser game launches.",
    website: "https://www.crazygames.com",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Fast web distribution", "Large browser audience", "Good fit for lightweight games"],
    weaknesses: ["Web-only constraints", "Platform-specific monetization model", "Short session focus"],
    bestFor: ["html5 games", "casual web titles", "rapid release cycles"],
    tags: ["deployment", "web", "browser", "game-jam"],
  },
  {
    name: "Poki",
    category: "deployment",
    description: "Web game publishing platform with a focus on polished, quick-loading browser experiences. Offers access to a broad casual audience.",
    website: "https://poki.com",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Large casual web audience", "Web-focused distribution", "Good for lightweight gameplay loops"],
    weaknesses: ["Web-only scope", "Editorial acceptance requirements", "Limited fit for deep premium games"],
    bestFor: ["casual web games", "html5 launches", "browser-first titles"],
    tags: ["deployment", "web", "browser", "casual"],
  },
  // AI TOOLING
  {
    name: "GitHub Copilot",
    category: "ai_tooling",
    description: "AI pair programmer integrated into VS Code, Visual Studio, JetBrains IDEs. Autocompletes code, suggests implementations, writes tests.",
    website: "https://github.com/features/copilot",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Excellent code autocomplete", "Works in your existing IDE", "Speeds up boilerplate", "Good at explaining code"],
    weaknesses: ["Monthly subscription cost", "Can suggest incorrect code", "Privacy concerns", "Less useful for engine-specific patterns"],
    bestFor: ["code generation", "all skill levels", "script writing", "productivity"],
    tags: ["ai", "code-generation", "ide", "productivity"],
  },
  {
    name: "Midjourney",
    category: "ai_tooling",
    description: "AI image generation tool via Discord. Produces high-quality concept art, textures, and visual references for game development.",
    website: "https://midjourney.com",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Extremely high quality output", "Fast concept generation", "Great for visual references", "Consistent art styles"],
    weaknesses: ["Subscription required", "Discord-based UI is awkward", "Commercial license terms vary", "Not pixel art focused"],
    bestFor: ["concept art", "texture references", "art direction", "prototyping visuals"],
    tags: ["ai", "art-generation", "concept-art", "textures"],
  },
  {
    name: "ChatGPT / GPT-4",
    category: "ai_tooling",
    description: "General-purpose AI assistant by OpenAI. Useful for game design brainstorming, dialog writing, game mechanics analysis, and code debugging.",
    website: "https://chat.openai.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Versatile: design, writing, code, analysis", "Free tier available", "Good at game design consulting", "Explains complex concepts"],
    weaknesses: ["Not game-engine specific", "Can hallucinate API details", "Requires good prompting"],
    bestFor: ["game design", "dialog writing", "brainstorming", "code help", "documentation"],
    tags: ["ai", "writing", "design", "brainstorming", "code-help"],
  },
  {
    name: "Cursor",
    category: "ai_tooling",
    description: "AI-first code editor built on VS Code with context-aware code generation and refactoring workflows. Useful for rapid scripting, codebase navigation, and implementation planning in game projects.",
    website: "https://cursor.com",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Strong codebase-aware generation", "Fast refactoring loops", "Familiar editor UX"],
    weaknesses: ["Paid tier for advanced usage", "Needs careful review of generated code", "IDE migration overhead"],
    bestFor: ["rapid prototyping", "gameplay scripting", "tools development"],
    tags: ["ai", "code-generation", "ide", "productivity"],
  },
  {
    name: "Claude Code",
    category: "ai_tooling",
    description: "Agentic coding workflow centered on repository-aware planning and code edits. It is useful for larger refactors, debugging sessions, and implementation tasks that span multiple files.",
    website: "https://www.anthropic.com/claude-code",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Strong long-context reasoning", "Good multi-file change support", "Useful for architecture-level tasks"],
    weaknesses: ["Output still needs validation", "Subscription cost", "Quality varies by prompt precision"],
    bestFor: ["multi-file refactors", "debugging", "technical planning"],
    tags: ["ai", "code-generation", "productivity", "tooling"],
  },
  {
    name: "Windsurf",
    category: "ai_tooling",
    description: "AI coding environment with integrated chat and command-style editing workflows. It helps teams iterate on gameplay logic, utility scripts, and project tooling quickly.",
    website: "https://windsurf.com",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Integrated AI editing flows", "Fast coding iteration", "Good for day-to-day developer productivity"],
    weaknesses: ["Subscription dependency", "Requires prompt discipline", "Feature set evolves quickly"],
    bestFor: ["indie workflows", "scripting", "tooling acceleration"],
    tags: ["ai", "code-generation", "ide", "productivity"],
  },
  {
    name: "v0.dev",
    category: "ai_tooling",
    description: "Prompt-to-UI generation tool that outputs component code for modern web stacks. Useful for quickly building dashboards, admin tools, and companion web experiences around games.",
    website: "https://v0.dev",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web", "pc"],
    strengths: ["Fast UI scaffolding", "Code output for real projects", "Good for internal tools"],
    weaknesses: ["Needs manual polish", "Best fit for web UI only", "Generated patterns may need refactor"],
    bestFor: ["live-ops dashboards", "community portals", "internal tooling"],
    tags: ["ai", "ui", "code-generation", "web"],
  },
  {
    name: "Lovable",
    category: "ai_tooling",
    description: "AI app builder focused on turning prompts into functional full-stack web experiences. It can accelerate prototype tools, player portals, and back-office flows for game teams.",
    website: "https://lovable.dev",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web", "pc"],
    strengths: ["Rapid app prototyping", "Beginner-accessible flow", "Useful for non-core tooling"],
    weaknesses: ["Not intended for engine runtime code", "Generated architecture may be generic", "Platform limits on customization"],
    bestFor: ["prototype web apps", "ops tools", "rapid validation"],
    tags: ["ai", "web", "rapid-prototyping", "beginner-friendly"],
  },
  {
    name: "Bolt.new",
    category: "ai_tooling",
    description: "Browser-based AI coding environment for rapidly generating and iterating on full-stack applications. Helpful for hackathon-grade utilities and gameplay-adjacent web products.",
    website: "https://bolt.new",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Fast browser workflow", "No local setup needed", "Good for quick MVP builds"],
    weaknesses: ["Limited for complex production architecture", "Token/cost limits", "Needs code review"],
    bestFor: ["hackathon tools", "prototype services", "small web utilities"],
    tags: ["ai", "web", "rapid-prototyping", "game-jam"],
  },
  {
    name: "Scenario.gg",
    category: "ai_tooling",
    description: "AI asset generation platform geared toward game teams with style consistency controls and pipeline-friendly outputs. Supports iterative creation of concept assets, icons, and textures.",
    website: "https://scenario.com",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["web", "pc"],
    strengths: ["Game-focused asset workflows", "Style control features", "Team-oriented pipeline support"],
    weaknesses: ["Subscription cost", "Prompt and dataset quality matter", "Requires curation and cleanup"],
    bestFor: ["concept assets", "icon packs", "texture ideation"],
    tags: ["ai", "art-generation", "game-dev", "2d"],
  },
  {
    name: "Leonardo.ai",
    category: "ai_tooling",
    description: "Generative image platform used for concept art, props, and style exploration with model and prompt controls. It helps teams reduce early ideation time before final art production.",
    website: "https://leonardo.ai",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Strong visual ideation speed", "Accessible UI", "Good style variation controls"],
    weaknesses: ["Quality can vary by prompt", "Licensing checks still needed", "Not a replacement for production polish"],
    bestFor: ["concept art", "moodboards", "visual exploration"],
    tags: ["ai", "art-generation", "concept-art", "2d"],
  },
  {
    name: "Suno",
    category: "ai_tooling",
    description: "AI music generation tool that can produce draft tracks and genre experiments quickly. Useful for placeholder soundtrack creation and rapid tone testing in prototypes.",
    website: "https://suno.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Fast music ideation", "Simple workflow", "Useful for early prototypes"],
    weaknesses: ["Licensing/commercial terms require review", "Limited fine-grained composition control", "Not a full DAW replacement"],
    bestFor: ["prototype soundtrack", "genre exploration", "temp music"],
    tags: ["ai", "audio", "music", "rapid-prototyping"],
  },
  {
    name: "Eleven Labs",
    category: "ai_tooling",
    description: "AI voice generation platform for creating narration, NPC lines, and placeholder localization voiceovers. Supports expressive TTS workflows and fast iteration on dialogue tone.",
    website: "https://elevenlabs.io",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["web", "pc"],
    strengths: ["High-quality TTS", "Fast voice iteration", "Useful for narrative prototypes"],
    weaknesses: ["Recurring cost", "Licensing and voice rights must be managed", "Audio cleanup still often required"],
    bestFor: ["npc dialogue prototypes", "narration", "temp voiceovers"],
    tags: ["ai", "audio", "tts", "narrative"],
  },
  {
    name: "Meshy",
    category: "ai_tooling",
    description: "AI 3D asset generation platform for creating quick meshes and textures from prompts or images. Good for early prototyping when teams need rapid placeholder assets.",
    website: "https://www.meshy.ai",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web", "pc"],
    strengths: ["Fast 3D ideation", "Prompt-based workflow", "Useful for placeholder assets"],
    weaknesses: ["Topology/UV quality may need manual cleanup", "Style consistency needs oversight", "Not final-quality for all assets"],
    bestFor: ["prototype 3d assets", "blocking scenes", "rapid content tests"],
    tags: ["ai", "3d", "asset-generation", "rapid-prototyping"],
  },
  {
    name: "Tripo3D",
    category: "ai_tooling",
    description: "AI model generation tool focused on turning images or prompts into 3D models quickly. Useful for concept blocking and early gameplay iteration.",
    website: "https://www.tripo3d.ai",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Quick image-to-3d flow", "Low barrier to entry", "Speeds up early content iteration"],
    weaknesses: ["Needs retopology for production", "Detail control is limited", "Output quality varies"],
    bestFor: ["3d placeholders", "prototype worlds", "concept testing"],
    tags: ["ai", "3d", "asset-generation", "game-jam"],
  },
  {
    name: "Inworld AI",
    category: "ai_tooling",
    description: "Character AI platform for creating real-time conversational NPCs with behavior and personality controls. Integrates into games to drive dynamic dialogue and interaction.",
    website: "https://inworld.ai",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "web", "console"],
    strengths: ["Real-time character interaction", "Game-focused SDK workflows", "Strong NPC dialogue use cases"],
    weaknesses: ["Complex integration", "Latency and cost considerations", "Design safeguards required"],
    bestFor: ["npc interaction systems", "narrative games", "immersive simulations"],
    tags: ["ai", "npc", "realtime", "narrative"],
  },
  {
    name: "Convai",
    category: "ai_tooling",
    description: "Conversational AI toolkit for adding voice and language-driven NPC interactions in games. Supports real-time character behavior and contextual responses.",
    website: "https://www.convai.com",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "web", "vr"],
    strengths: ["Voice-first NPC workflows", "Realtime interaction support", "Good fit for immersive experiences"],
    weaknesses: ["Advanced integration effort", "Operational cost for scale", "Needs narrative and moderation design"],
    bestFor: ["vr social experiences", "narrative prototypes", "ai-driven npcs"],
    tags: ["ai", "npc", "realtime", "vr"],
  },
  {
    name: "Rosebud AI",
    category: "ai_tooling",
    description: "AI-assisted game creation platform oriented around rapid concept-to-playable workflows. Helpful for experimenting with mechanics and creative direction quickly.",
    website: "https://rosebud.ai",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web", "pc"],
    strengths: ["Fast concept iteration", "Beginner-accessible workflow", "Good for quick experimentation"],
    weaknesses: ["Limited customization for advanced teams", "Prototype-first scope", "Output quality can vary"],
    bestFor: ["idea validation", "game-jam concepts", "rapid prototypes"],
    tags: ["ai", "rapid-prototyping", "beginner-friendly", "game-jam"],
  },
  {
    name: "Layer.ai",
    category: "ai_tooling",
    description: "AI platform for generating and managing game art assets with collaboration and style consistency features. Focused on production workflows for art teams.",
    website: "https://www.layer.ai",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["web", "pc"],
    strengths: ["Team-oriented art pipeline support", "Style consistency controls", "Game-focused asset workflows"],
    weaknesses: ["Subscription cost", "Curation still required", "Workflow setup overhead"],
    bestFor: ["art pipelines", "asset iteration", "team collaboration"],
    tags: ["ai", "art-generation", "game-dev", "cloud"],
  },
  {
    name: "Promethean AI",
    category: "ai_tooling",
    description: "AI assistant for environment art and scene assembly in 3D workflows. Helps place, organize, and iterate level dressing faster inside content pipelines.",
    website: "https://www.prometheanai.com",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Environment art acceleration", "Useful for scene composition", "Pipeline-friendly for larger teams"],
    weaknesses: ["Advanced tooling setup", "Best value in larger productions", "Subscription dependency"],
    bestFor: ["environment art", "level dressing", "3d production pipelines"],
    tags: ["ai", "3d", "environment", "technical-art"],
  },
  {
    name: "Charisma.ai",
    category: "ai_tooling",
    description: "Narrative AI platform for building interactive story logic and conversational experiences. Useful for branching dialogue-heavy games and immersive training simulations.",
    website: "https://charisma.ai",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["web", "pc", "mobile", "vr"],
    strengths: ["Narrative-focused tooling", "Interactive dialogue workflows", "Good for branching experiences"],
    weaknesses: ["Requires narrative design effort", "Platform cost", "Integration complexity for full productions"],
    bestFor: ["interactive storytelling", "dialogue systems", "immersive narrative experiences"],
    tags: ["ai", "narrative", "dialogue", "realtime"],
  },
  {
    name: "Krea",
    category: "ai_tooling",
    description: "Real-time generative visual tool for fast concept iteration and style exploration. Useful in pre-production for visual direction experiments.",
    website: "https://www.krea.ai",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Realtime visual ideation", "Fast concept iteration", "Accessible interface"],
    weaknesses: ["Asset quality varies", "Needs post-processing for production", "Licensing checks still needed"],
    bestFor: ["art direction", "concept exploration", "visual brainstorming"],
    tags: ["ai", "art-generation", "concept-art", "beginner-friendly"],
  },
  {
    name: "Runway",
    category: "ai_tooling",
    description: "AI video and media generation suite for cinematic mockups, trailers, and visual experiments. Useful for pitch decks and previsualization workflows.",
    website: "https://runwayml.com",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["web", "pc"],
    strengths: ["Strong generative video tools", "Good for previs and marketing prototypes", "Fast iteration"],
    weaknesses: ["Subscription/token cost", "Not engine-runtime tooling", "Output may require heavy editing"],
    bestFor: ["cinematic mockups", "marketing previews", "previsualization"],
    tags: ["ai", "video", "cinematic", "prototype"],
  },
  {
    name: "Move.ai",
    category: "ai_tooling",
    description: "Markerless motion capture platform that turns camera footage into animation-ready motion data. Speeds up character animation prototyping without full mocap stages.",
    website: "https://www.move.ai",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Markerless mocap workflow", "Faster than traditional stage setups", "Good for prototype animation capture"],
    weaknesses: ["Capture quality depends on setup", "Post-cleanup often required", "Paid service"],
    bestFor: ["character animation prototyping", "indie mocap workflows", "cinematic iteration"],
    tags: ["ai", "animation", "mocap", "3d"],
  },
  // AUDIO
  {
    name: "FMOD Studio",
    category: "audio",
    description: "Professional interactive audio middleware used to author adaptive music and sound behavior in games. Integrates with major engines and supports parameter-driven mixing.",
    website: "https://www.fmod.com",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console", "vr", "cross-platform"],
    strengths: ["Mature interactive audio workflows", "Strong engine integrations", "Adaptive mixing support"],
    weaknesses: ["Learning curve for non-audio teams", "License cost at scale", "Middleware integration overhead"],
    bestFor: ["adaptive music", "interactive sound design", "cross-platform titles"],
    tags: ["audio", "middleware", "realtime", "cross-platform"],
  },
  {
    name: "Wwise",
    category: "audio",
    description: "Industry-standard game audio middleware for interactive music, voice, and effects with deep profiling tools. Common in mid-size and AAA production pipelines.",
    website: "https://www.audiokinetic.com/products/wwise",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "console", "vr", "cross-platform"],
    strengths: ["Production-proven middleware", "Advanced profiling and optimization", "Scales well for large projects"],
    weaknesses: ["Complex setup", "Steeper onboarding", "License complexity for teams"],
    bestFor: ["aaa audio pipelines", "complex interactive music", "performance-sensitive audio systems"],
    tags: ["audio", "middleware", "aaa", "cross-platform"],
  },
  {
    name: "Audacity",
    category: "audio",
    description: "Free open-source audio editor for waveform editing, cleanup, and quick mastering tasks. Useful for indie teams handling simple sound effects and voice prep.",
    website: "https://www.audacityteam.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["pc", "cross-platform"],
    strengths: ["Free and open source", "Simple editing workflow", "Good for quick cleanup tasks"],
    weaknesses: ["Not a full production DAW", "Limited advanced workflow automation", "UI can feel basic"],
    bestFor: ["voice cleanup", "basic sfx editing", "budget teams"],
    tags: ["audio", "open-source", "beginner-friendly", "tooling"],
  },
  {
    name: "Reaper",
    category: "audio",
    description: "Lightweight full-featured DAW widely used for game audio production and editing. Offers deep routing, scripting, and plugin support at a relatively low cost.",
    website: "https://www.reaper.fm",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc", "cross-platform"],
    strengths: ["Powerful DAW features", "Efficient performance", "Strong plugin and scripting support"],
    weaknesses: ["UI less polished than some DAWs", "Requires setup for optimal workflow", "Audio-specialist learning curve"],
    bestFor: ["sound design", "music production", "voice editing"],
    tags: ["audio", "daw", "production", "tooling"],
  },
  {
    name: "Soundly",
    category: "audio",
    description: "Cloud-connected sound effects library and browsing tool designed for fast search and drag-drop workflow. Helps teams source and organize production-ready SFX quickly.",
    website: "https://getsoundly.com",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["pc", "cross-platform"],
    strengths: ["Fast SFX discovery", "Large searchable library", "Simple integration into editing workflows"],
    weaknesses: ["Subscription cost", "Library dependence", "Requires license management discipline"],
    bestFor: ["sfx sourcing", "rapid audio iteration", "small audio teams"],
    tags: ["audio", "library", "cloud", "beginner-friendly"],
  },
  {
    name: "BFXR",
    category: "audio",
    description: "Retro sound effect generator focused on quick arcade-style bleeps, impacts, and UI cues. Commonly used in game jams and pixel-art projects.",
    website: "https://www.bfxr.net",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["pc"],
    strengths: ["Very fast SFX generation", "Great for retro styles", "Beginner-friendly workflow"],
    weaknesses: ["Narrow stylistic range", "Limited realism", "Simple feature set"],
    bestFor: ["game jams", "retro effects", "quick ui sounds"],
    tags: ["audio", "retro", "game-jam", "beginner-friendly"],
  },
  {
    name: "Eleven Labs TTS",
    category: "audio",
    description: "Text-to-speech platform for generating narration and character voice placeholders with expressive output. Useful for iterating dialogue timing before final recording.",
    website: "https://elevenlabs.io",
    pricing: "subscription",
    minSkillLevel: "beginner",
    platforms: ["web", "pc"],
    strengths: ["High-quality voice generation", "Fast iteration on script changes", "Good for prototype VO"],
    weaknesses: ["Ongoing subscription cost", "Rights/compliance checks required", "Final polish may need manual editing"],
    bestFor: ["narration prototypes", "temp npc voice", "localization experiments"],
    tags: ["audio", "ai", "tts", "narrative"],
  },
  {
    name: "Suno Music",
    category: "audio",
    description: "AI music generation tool for quickly drafting soundtrack ideas and mood references. Useful in early production for testing pacing and tone before bespoke composition.",
    website: "https://suno.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["web"],
    strengths: ["Rapid music concepting", "Simple prompt workflow", "Helpful for temporary tracks"],
    weaknesses: ["Limited arrangement control", "Licensing review needed", "Not a replacement for final composition in many projects"],
    bestFor: ["temp soundtrack", "mood testing", "prototype audio"],
    tags: ["audio", "ai", "music", "rapid-prototyping"],
  },
  // NETWORKING
  {
    name: "Photon Fusion",
    category: "networking",
    description: "Real-time multiplayer networking SDK with authoritative and shared simulation options. Popular for fast-paced online game prototypes and production titles.",
    website: "https://www.photonengine.com/fusion",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "web", "console", "vr", "cross-platform"],
    strengths: ["Mature real-time networking stack", "Scalable cloud infrastructure options", "Good Unity ecosystem support"],
    weaknesses: ["Network engineering complexity", "Recurring cost", "Advanced replication concepts required"],
    bestFor: ["real-time multiplayer", "competitive games", "cross-platform sessions"],
    tags: ["networking", "multiplayer", "realtime", "cloud"],
  },
  {
    name: "Mirror Networking",
    category: "networking",
    description: "Open-source high-level networking library for Unity derived from UNet concepts. Gives teams self-hosted flexibility with community-driven tooling.",
    website: "https://mirror-networking.com",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Open-source and flexible", "Unity-focused API familiarity", "Good for custom server control"],
    weaknesses: ["Requires backend ops decisions", "Performance tuning is team responsibility", "Smaller support footprint than managed services"],
    bestFor: ["indie multiplayer", "self-hosted networking", "unity online prototypes"],
    tags: ["networking", "multiplayer", "open-source", "unity"],
  },
  {
    name: "Unity Netcode for GameObjects",
    category: "networking",
    description: "Unity's official multiplayer framework for synchronized gameplay objects and RPC workflows. Integrated with Unity services and tooling for online game features.",
    website: "https://docs.unity3d.com/Packages/com.unity.netcode.gameobjects",
    pricing: "free",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Official Unity support", "Integrated workflow", "Good onboarding for Unity teams"],
    weaknesses: ["Unity-specific approach", "Still requires network architecture expertise", "Feature tradeoffs vs third-party stacks"],
    bestFor: ["unity multiplayer", "co-op games", "official-stack workflows"],
    tags: ["networking", "multiplayer", "unity", "realtime"],
  },
  {
    name: "Nakama",
    category: "networking",
    description: "Open-source server for social and real-time multiplayer backends with authentication, storage, and matchmaker features. Supports authoritative server logic and live ops workflows.",
    website: "https://heroiclabs.com/nakama",
    pricing: "open_source",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "web", "console", "cross-platform"],
    strengths: ["Comprehensive backend + realtime stack", "Open-source deployment control", "Strong live-ops primitives"],
    weaknesses: ["Infrastructure ownership burden", "Advanced backend setup", "Requires operational maturity"],
    bestFor: ["online games", "social features", "authoritative backends"],
    tags: ["networking", "backend", "realtime", "open-source", "cloud"],
  },
  {
    name: "Colyseus",
    category: "networking",
    description: "Open-source multiplayer framework for Node.js with room-based state synchronization. Popular for web and mobile multiplayer prototypes.",
    website: "https://www.colyseus.io",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["web", "mobile", "pc", "cross-platform"],
    strengths: ["Fast setup for room-based games", "Good JavaScript/TypeScript ergonomics", "Open-source flexibility"],
    weaknesses: ["Requires server deployment management", "Scaling strategy needed", "Less out-of-box enterprise tooling"],
    bestFor: ["web multiplayer", "indie real-time games", "typescript backends"],
    tags: ["networking", "realtime", "web", "open-source", "typescript"],
  },
  {
    name: "Amazon GameLift",
    category: "networking",
    description: "Managed AWS service for deploying, scaling, and operating dedicated game servers. Designed for production multiplayer infrastructure and matchmaking workflows.",
    website: "https://aws.amazon.com/gamelift",
    pricing: "paid",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Managed dedicated server scaling", "Production-ready cloud tooling", "AWS ecosystem integration"],
    weaknesses: ["Cloud cost management complexity", "AWS operational expertise required", "Vendor lock-in considerations"],
    bestFor: ["dedicated server games", "scalable multiplayer", "production live operations"],
    tags: ["networking", "cloud", "multiplayer", "backend"],
  },
  // BACKEND SERVICES
  {
    name: "PlayFab",
    category: "backend_services",
    description: "Game backend platform providing player accounts, economy, analytics, and live operations tooling. Commonly used for mobile and cross-platform online features.",
    website: "https://playfab.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web", "console", "cross-platform"],
    strengths: ["Game-specific backend features", "Strong live-ops capabilities", "Microsoft ecosystem support"],
    weaknesses: ["Service coupling", "Cost can grow with scale", "Integration complexity for custom flows"],
    bestFor: ["live service games", "player economy", "cross-platform backend features"],
    tags: ["backend", "cloud", "live-ops", "game-dev"],
  },
  {
    name: "Unity Gaming Services",
    category: "backend_services",
    description: "Suite of Unity-hosted backend services including auth, cloud save, lobby, relay, and economy modules. Tight integration for teams building fully inside Unity.",
    website: "https://unity.com/solutions/gaming-services",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Strong Unity integration", "Broad service catalog", "Faster setup for Unity-first teams"],
    weaknesses: ["Unity ecosystem lock-in", "Usage costs at scale", "Service maturity varies by module"],
    bestFor: ["unity live ops", "multiplayer support services", "cloud save and economy"],
    tags: ["backend", "unity", "cloud", "live-ops"],
  },
  {
    name: "GameSparks",
    category: "backend_services",
    description: "Backend service platform for player management, virtual economy, and social systems in games. Used for reducing custom server workload in live products.",
    website: "https://aws.amazon.com/gamesparks",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "web", "console", "cross-platform"],
    strengths: ["Game-oriented backend features", "Live-service support patterns", "Managed service approach"],
    weaknesses: ["Platform roadmap dependency", "Cost considerations", "Customization limits compared with full custom backends"],
    bestFor: ["player data services", "economy systems", "managed backend workflows"],
    tags: ["backend", "cloud", "game-dev", "live-ops"],
  },
  {
    name: "Firebase",
    category: "backend_services",
    description: "Google backend platform with authentication, database, cloud functions, and analytics integrations. Useful for rapid MVP backends and mobile-centric game services.",
    website: "https://firebase.google.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["mobile", "web", "pc", "cross-platform"],
    strengths: ["Rapid setup", "Strong mobile support", "Broad managed services"],
    weaknesses: ["Game-specific features are limited", "Vendor lock-in risk", "Cost can spike with usage patterns"],
    bestFor: ["mvp backends", "mobile game services", "quick auth and data storage"],
    tags: ["backend", "cloud", "beginner-friendly", "mobile"],
  },
  {
    name: "Supabase",
    category: "backend_services",
    description: "Open-source backend platform with Postgres database, auth, storage, and realtime APIs. Good for teams that want SQL-centric control with managed convenience.",
    website: "https://supabase.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["web", "mobile", "pc", "cross-platform"],
    strengths: ["Postgres-first architecture", "Open-source core", "Good developer ergonomics"],
    weaknesses: ["Needs schema/ops design discipline", "Not game-specific out of the box", "Realtime scaling planning required"],
    bestFor: ["custom backend features", "sql-first teams", "rapid service prototyping"],
    tags: ["backend", "cloud", "open-source", "realtime"],
  },
  {
    name: "Beamable",
    category: "backend_services",
    description: "Game backend platform with Unity-focused workflows for accounts, inventory, commerce, and live operations. Helps teams ship live features without building every service from scratch.",
    website: "https://beamable.com",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Game-specific backend modules", "Unity-friendly tooling", "Live-ops support"],
    weaknesses: ["Service dependence", "Subscription cost", "Advanced custom flows may need deeper integration work"],
    bestFor: ["unity live services", "inventory and economy", "faster backend delivery"],
    tags: ["backend", "cloud", "unity", "live-ops"],
  },
  // MONETIZATION
  {
    name: "AppLovin MAX",
    category: "monetization",
    description: "Mediation platform for in-app ads with network optimization and revenue tooling. Widely used in mobile free-to-play monetization stacks.",
    website: "https://www.applovin.com/max",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["mobile"],
    strengths: ["Strong ad mediation features", "Revenue optimization tooling", "Broad ad network integrations"],
    weaknesses: ["Integration complexity", "Policy and compliance overhead", "Best fit mainly for ad-driven products"],
    bestFor: ["mobile f2p monetization", "ad mediation", "revenue optimization"],
    tags: ["monetization", "ads", "mobile", "analytics"],
  },
  {
    name: "Unity LevelPlay",
    category: "monetization",
    description: "Unity's ad mediation solution for managing ad demand sources and improving ad revenue performance. Integrates with Unity-centric production workflows.",
    website: "https://unity.com/products/levelplay",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["mobile"],
    strengths: ["Unity ecosystem integration", "Ad mediation and waterfall tooling", "Mobile monetization focus"],
    weaknesses: ["Primarily mobile ad use cases", "Optimization requires iteration", "Platform coupling"],
    bestFor: ["unity mobile games", "ad monetization", "f2p optimization"],
    tags: ["monetization", "ads", "mobile", "unity"],
  },
  {
    name: "AdMob",
    category: "monetization",
    description: "Google mobile ad platform for banner, interstitial, and rewarded ad placements. Common baseline for monetizing casual and midcore mobile games.",
    website: "https://admob.google.com",
    pricing: "free",
    minSkillLevel: "beginner",
    platforms: ["mobile"],
    strengths: ["Simple onboarding", "Large ad network reach", "Good documentation"],
    weaknesses: ["Revenue depends on fill and region mix", "Policy compliance requirements", "Limited outside mobile"],
    bestFor: ["mobile ad monetization", "indie f2p games", "rewarded ad flows"],
    tags: ["monetization", "ads", "mobile", "beginner-friendly"],
  },
  {
    name: "Xsolla",
    category: "monetization",
    description: "Commerce and payment platform for game monetization including web shops, subscriptions, and virtual goods flows. Useful for cross-platform revenue outside app-store rails.",
    website: "https://xsolla.com",
    pricing: "paid",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "web", "console", "cross-platform"],
    strengths: ["Game-focused commerce tooling", "Flexible payment options", "Supports direct-to-player strategies"],
    weaknesses: ["Integration overhead", "Operational/legal setup complexity", "Best value in larger monetization programs"],
    bestFor: ["web shops", "cross-platform commerce", "live service monetization"],
    tags: ["monetization", "payments", "commerce", "cross-platform"],
  },
  {
    name: "Stripe",
    category: "monetization",
    description: "General-purpose payment infrastructure for subscriptions, checkouts, and digital transactions. Useful for web stores, memberships, and creator-side monetization around games.",
    website: "https://stripe.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["web", "pc", "mobile", "cross-platform"],
    strengths: ["Developer-friendly APIs", "Global payment support", "Reliable checkout tooling"],
    weaknesses: ["Not game-specific", "Compliance and tax workflows still needed", "Fees impact margins"],
    bestFor: ["web payments", "subscriptions", "creator storefronts"],
    tags: ["monetization", "payments", "web", "cloud"],
  },
  // ANALYTICS
  {
    name: "GameAnalytics",
    category: "analytics",
    description: "Analytics platform purpose-built for games with event tracking and monetization insights. Supports dashboards for retention, progression, and economy tuning.",
    website: "https://gameanalytics.com",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "web", "console", "cross-platform"],
    strengths: ["Game-specific analytics model", "Beginner-friendly integration", "Useful retention and monetization insights"],
    weaknesses: ["Advanced custom analysis may need external tooling", "Event taxonomy design still required", "Feature depth varies by plan"],
    bestFor: ["indie analytics", "retention tracking", "game economy monitoring"],
    tags: ["analytics", "game-dev", "cloud", "beginner-friendly"],
  },
  {
    name: "deltaDNA",
    category: "analytics",
    description: "Game analytics and player segmentation platform focused on live-ops decisions and personalization. Helps teams trigger targeted offers and progression interventions.",
    website: "https://deltadna.com",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Strong segmentation workflows", "Live-ops decision support", "Monetization optimization use cases"],
    weaknesses: ["Advanced setup and strategy required", "Subscription cost", "Needs disciplined event design"],
    bestFor: ["live-ops optimization", "player segmentation", "personalized offers"],
    tags: ["analytics", "live-ops", "monetization", "cloud"],
  },
  {
    name: "Amplitude",
    category: "analytics",
    description: "Product analytics suite for behavior tracking, funnels, and cohort analysis across digital products. Useful for game companion apps and data-driven feature decisions.",
    website: "https://amplitude.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["web", "mobile", "pc", "cross-platform"],
    strengths: ["Strong funnel and cohort analysis", "Mature product analytics workflows", "Good experimentation support"],
    weaknesses: ["Not game-specific by default", "Event schema planning required", "Cost at higher data volumes"],
    bestFor: ["feature analytics", "behavior analysis", "companion app metrics"],
    tags: ["analytics", "cloud", "experimentation", "product"],
  },
  {
    name: "Mixpanel",
    category: "analytics",
    description: "Event analytics platform for user behavior analysis, funnels, and retention reporting. Helps teams monitor onboarding and conversion performance.",
    website: "https://mixpanel.com",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["web", "mobile", "pc", "cross-platform"],
    strengths: ["Flexible event analysis", "Good retention/funnel tooling", "Developer-friendly SDKs"],
    weaknesses: ["Generic analytics model", "Data governance work needed", "Scaling cost considerations"],
    bestFor: ["funnel analysis", "retention metrics", "feature adoption tracking"],
    tags: ["analytics", "cloud", "retention", "product"],
  },
  {
    name: "Unity Analytics",
    category: "analytics",
    description: "Unity-integrated analytics solution for gameplay events, funnels, and live-ops signals. Designed for teams that want analytics directly in Unity workflows.",
    website: "https://unity.com/products/analytics",
    pricing: "freemium",
    minSkillLevel: "beginner",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Native Unity workflow integration", "Quick setup for Unity projects", "Useful gameplay event tracking"],
    weaknesses: ["Unity-centric scope", "Advanced reporting may require additional tools", "Service-plan constraints"],
    bestFor: ["unity projects", "event tracking", "live-ops metrics"],
    tags: ["analytics", "unity", "cloud", "beginner-friendly"],
  },
  // NARRATIVE
  {
    name: "Twine",
    category: "narrative",
    description: "Open-source tool for creating branching interactive stories with a visual passage graph. Excellent for narrative prototyping and writing-first game design.",
    website: "https://twinery.org",
    pricing: "open_source",
    minSkillLevel: "beginner",
    platforms: ["web", "pc"],
    strengths: ["Very easy narrative prototyping", "Visual branching workflow", "Free and open source"],
    weaknesses: ["Limited for large runtime systems without custom integration", "UI/formatting constraints", "Needs export/integration planning"],
    bestFor: ["interactive fiction", "branching prototype writing", "narrative design exploration"],
    tags: ["narrative", "writing", "open-source", "beginner-friendly"],
  },
  {
    name: "Ink (inkle)",
    category: "narrative",
    description: "Scripting language for branching narrative and dialogue with robust tooling and engine integrations. Widely used for story-heavy games requiring maintainable narrative logic.",
    website: "https://www.inklestudios.com/ink",
    pricing: "free",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Powerful branching text model", "Production-proven in shipped games", "Good integration support"],
    weaknesses: ["Scripting syntax learning curve", "Narrative architecture discipline required", "Non-writer teams may need onboarding"],
    bestFor: ["branching dialogue", "story-driven games", "narrative systems"],
    tags: ["narrative", "dialogue", "branching", "writing"],
  },
  {
    name: "Yarn Spinner",
    category: "narrative",
    description: "Dialogue scripting system designed for games, with strong Unity adoption and node-based conversation authoring patterns. Good for character-heavy projects.",
    website: "https://www.yarnspinner.dev",
    pricing: "open_source",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Game-focused dialogue authoring", "Strong Unity support", "Open-source and extensible"],
    weaknesses: ["Integration work still required", "Narrative tooling setup takes planning", "Best for dialogue-centric use cases"],
    bestFor: ["dialogue-heavy games", "npc conversations", "unity narrative systems"],
    tags: ["narrative", "dialogue", "unity", "open-source"],
  },
  {
    name: "Articy:draft 3",
    category: "narrative",
    description: "Professional narrative design suite for story structure, quest logic, and dialogue management. Common in larger productions that require writer-designer collaboration.",
    website: "https://www.articy.com/en",
    pricing: "paid",
    minSkillLevel: "advanced",
    platforms: ["pc"],
    strengths: ["Comprehensive narrative planning", "Visual story architecture tools", "Team collaboration support"],
    weaknesses: ["Paid licensing", "Complex tooling for small projects", "Integration/export workflow overhead"],
    bestFor: ["large narrative projects", "quest design", "writer-designer pipelines"],
    tags: ["narrative", "writing", "quest-design", "professional"],
  },
  {
    name: "ChatMapper",
    category: "narrative",
    description: "Dialogue and branching conversation editor for game narrative workflows. Useful for organizing large conversation trees and localization-aware writing.",
    website: "https://www.chatmapper.com",
    pricing: "paid",
    minSkillLevel: "intermediate",
    platforms: ["pc"],
    strengths: ["Good conversation tree management", "Mature narrative workflow", "Useful export options"],
    weaknesses: ["Paid software", "Legacy UX in some areas", "Integration work required per engine"],
    bestFor: ["branching dialogue trees", "narrative organization", "localized conversation content"],
    tags: ["narrative", "dialogue", "writing", "tooling"],
  },
  // BUILD / CI
  {
    name: "Unity Cloud Build",
    category: "build_ci",
    description: "Managed build automation service for Unity projects across target platforms. Reduces manual build overhead and supports continuous delivery workflows.",
    website: "https://unity.com/solutions/unity-cloud-build",
    pricing: "subscription",
    minSkillLevel: "intermediate",
    platforms: ["pc", "mobile", "console", "cross-platform"],
    strengths: ["Unity-native CI flow", "Automated multi-platform builds", "Saves local machine time"],
    weaknesses: ["Subscription cost", "Unity-centric limitations", "Build pipeline customization constraints"],
    bestFor: ["unity ci", "automated builds", "small-to-mid teams"],
    tags: ["build", "ci-cd", "unity", "cloud"],
  },
  {
    name: "GameCI (Docker)",
    category: "build_ci",
    description: "Open-source CI tooling for Unity using Docker images and scripted pipelines. Enables reproducible builds in GitHub Actions, GitLab CI, and other runners.",
    website: "https://game.ci",
    pricing: "open_source",
    minSkillLevel: "advanced",
    platforms: ["pc", "mobile", "web", "console", "cross-platform"],
    strengths: ["Reproducible automated Unity builds", "Works across multiple CI providers", "Open-source flexibility"],
    weaknesses: ["Advanced CI setup required", "Docker and licensing configuration complexity", "Maintenance burden on team"],
    bestFor: ["self-managed ci pipelines", "unity automation", "reproducible builds"],
    tags: ["build", "ci-cd", "open-source", "unity", "automation"],
  },
  {
    name: "GitHub Actions",
    category: "build_ci",
    description: "Workflow automation platform integrated with GitHub repositories for build, test, and deployment pipelines. Useful for code, content checks, and release automation.",
    website: "https://github.com/features/actions",
    pricing: "freemium",
    minSkillLevel: "intermediate",
    platforms: ["pc", "cross-platform"],
    strengths: ["Tight GitHub integration", "Large ecosystem of actions", "Scales from simple to complex pipelines"],
    weaknesses: ["Minutes cost at scale", "Workflow debugging can be complex", "Requires CI design discipline"],
    bestFor: ["ci-cd automation", "build validation", "release workflows"],
    tags: ["build", "ci-cd", "automation", "cloud"],
  },
  {
    name: "Buildkite",
    category: "build_ci",
    description: "Hybrid CI platform with hosted control plane and self-hosted agents for flexible pipeline execution. Common for studios requiring strict control over build infrastructure.",
    website: "https://buildkite.com",
    pricing: "subscription",
    minSkillLevel: "advanced",
    platforms: ["pc", "cross-platform"],
    strengths: ["Powerful pipeline customization", "Self-hosted agent control", "Good for large teams"],
    weaknesses: ["Infrastructure management required", "Higher setup complexity", "Cost and ops overhead"],
    bestFor: ["studio-grade ci", "custom infrastructure", "high-control build pipelines"],
    tags: ["build", "ci-cd", "automation", "enterprise"],
  },
];

export const TOOL_CATEGORIES = [
  { id: "engine", label: "Game Engine", description: "Core engine powering your game's rendering, physics, and scene management" },
  { id: "programming", label: "Programming Language", description: "Primary scripting and programming language for game logic" },
  { id: "art", label: "Art & Assets", description: "Tools for creating 2D/3D art, textures, and visual assets" },
  { id: "animation", label: "Animation", description: "Character and object animation tools" },
  { id: "ui", label: "UI / HUD", description: "User interface and heads-up display systems" },
  { id: "vfx", label: "VFX & Particles", description: "Visual effects, particle systems, and post-processing" },
  { id: "version_control", label: "Version Control", description: "Source control and collaboration for code and assets" },
  { id: "deployment", label: "Deployment & Distribution", description: "Platforms and stores for publishing your game" },
  { id: "ai_tooling", label: "AI Tooling", description: "AI-powered tools for accelerating development" },
  { id: "audio", label: "Audio", description: "Music, sound effects, voice, and interactive audio tooling" },
  { id: "networking", label: "Networking", description: "Multiplayer networking frameworks, services, and dedicated server platforms" },
  { id: "backend_services", label: "Backend Services", description: "Managed backend platforms for auth, economy, storage, and live operations" },
  { id: "monetization", label: "Monetization", description: "Ads, payments, and commerce platforms for game revenue" },
  { id: "analytics", label: "Analytics", description: "Player behavior, retention, and monetization analytics tools" },
  { id: "narrative", label: "Narrative", description: "Interactive story, dialogue, and quest authoring tools" },
  { id: "build_ci", label: "Build & CI", description: "Build automation, continuous integration, and release pipeline tools" },
];
